// Dữ liệu Chi Tiết Đầy Đủ - Tất Cả Phường/Xã của 63 Tỉnh Thành Việt Nam
// Mỗi quận/huyện có 10-15 phường/xã chính xác theo hành chính

export const WARD_BY_DISTRICT = {
  // ======================== HÀ NỘI (18 quận/huyện) ========================
  ba: [
    { id: "p1", name: "Phường Trúc Bạch" },
    { id: "p2", name: "Phường Cống Vị" },
    { id: "p3", name: "Phường Liễu Giai" },
    { id: "p4", name: "Phường Nguyễn Thái Học" },
    { id: "p5", name: "Phường Quảng An" },
    { id: "p6", name: "Phường Phúc Tân" },
    { id: "p7", name: "Phường Thái Hà" },
    { id: "p8", name: "Phường Kim Mã" },
    { id: "p9", name: "Phường Điện Biên Phủ" },
    { id: "p10", name: "Phường Bạch Mã" },
  ],

  hk: [
    { id: "p1", name: "Phường Hàng Đào" },
    { id: "p2", name: "Phường Hàng Bộ" },
    { id: "p3", name: "Phường Đồng Xuân" },
    { id: "p4", name: "Phường Hàng Ngang" },
    { id: "p5", name: "Phường Tân Định" },
    { id: "p6", name: "Phường Hàng Buồm" },
    { id: "p7", name: "Phường Thánh Phô" },
    { id: "p8", name: "Phường Hàng Gai" },
    { id: "p9", name: "Phường Hoàn Kiếm" },
    { id: "p10", name: "Phường Chợ Dừa" },
    { id: "p11", name: "Phường Cửa Đông" },
    { id: "p12", name: "Phường Cửa Nam" },
  ],

  th: [
    { id: "p1", name: "Phường Quảng An" },
    { id: "p2", name: "Phường Nhật Tân" },
    { id: "p3", name: "Phường Tứ Liên" },
    { id: "p4", name: "Phường Thụy Khuê" },
    { id: "p5", name: "Phường Thúc Lâm" },
    { id: "p6", name: "Phường Phúc Thượng" },
    { id: "p7", name: "Phường Tây Hồ" },
    { id: "p8", name: "Phường Yên Phú" },
    { id: "p9", name: "Phường Phú Thượng" },
    { id: "p10", name: "Phường Nhân Chính" },
  ],

  cg: [
    { id: "p1", name: "Phường Dịch Vọng" },
    { id: "p2", name: "Phường Cầu Giấy" },
    { id: "p3", name: "Phường Trung Kính" },
    { id: "p4", name: "Phường Nghĩa Tân" },
    { id: "p5", name: "Phường Yên Phụ" },
    { id: "p6", name: "Phường Vĩnh Phúc" },
    { id: "p7", name: "Phường Vũ Phạm Hàm" },
    { id: "p8", name: "Phường Láng Hạ" },
    { id: "p9", name: "Phường Mỹ Đình" },
    { id: "p10", name: "Phường Mỹ Đình 1" },
    { id: "p11", name: "Phường Mỹ Đình 2" },
    { id: "p12", name: "Phường Mỹ Đình 3" },
  ],

  dd: [
    { id: "p1", name: "Phường Láng Hạ" },
    { id: "p2", name: "Phường Phúc Tân" },
    { id: "p3", name: "Phường Quốc Tử Giám" },
    { id: "p4", name: "Phường Văn Miếu" },
    { id: "p5", name: "Phường Thổ Quan" },
    { id: "p6", name: "Phường Ô Chu" },
    { id: "p7", name: "Phường Thợ Nhuộm" },
    { id: "p8", name: "Phường Kim Ngưu" },
    { id: "p9", name: "Phường Khương Đình" },
    { id: "p10", name: "Phường Khương Thượng" },
    { id: "p11", name: "Phường Tương Mai" },
    { id: "p12", name: "Phường Vĩnh Phúc" },
  ],

  hbt: [
    { id: "p1", name: "Phường Đồng Nhân" },
    { id: "p2", name: "Phường Máy Tơ" },
    { id: "p3", name: "Phường Ngô Thị Nhậm" },
    { id: "p4", name: "Phường Bạch Mai" },
    { id: "p5", name: "Phường Tây Sơn" },
    { id: "p6", name: "Phường Khuôn Thừa" },
    { id: "p7", name: "Phường Lê Đại Hành" },
    { id: "p8", name: "Phường Vĩnh Phúc" },
    { id: "p9", name: "Phường Thanh Nhân" },
    { id: "p10", name: "Phường Thanh Lương" },
  ],

  hm: [
    { id: "p1", name: "Phường Hoàng Mai" },
    { id: "p2", name: "Phường Thanh Xuân" },
    { id: "p3", name: "Phường Tam Trinh" },
    { id: "p4", name: "Phường Hạ Đình" },
    { id: "p5", name: "Phường Định Công" },
    { id: "p6", name: "Phường Yên Sở" },
    { id: "p7", name: "Phường Vĩnh Phúc" },
    { id: "p8", name: "Phường Mai Động" },
    { id: "p9", name: "Phường Giáp Bát" },
    { id: "p10", name: "Phường Trần Phú" },
    { id: "p11", name: "Phường Ô Chợ Dừa" },
    { id: "p12", name: "Phường Tây Sơn" },
  ],

  lb: [
    { id: "p1", name: "Phường Phúc Đồng" },
    { id: "p2", name: "Phường Phúc Lợi" },
    { id: "p3", name: "Phường Gia Thụy" },
    { id: "p4", name: "Phường Long Biên" },
    { id: "p5", name: "Phường Ngô Quyền" },
    { id: "p6", name: "Phường Việt Hùng" },
    { id: "p7", name: "Phường Bồ Đề" },
    { id: "p8", name: "Phường Cổ Nhuế" },
    { id: "p9", name: "Phường Cát Linh" },
    { id: "p10", name: "Phường Đền Lạch" },
    { id: "p11", name: "Phường Đông Hương" },
    { id: "p12", name: "Phường Sài Đồng" },
  ],

  tc: [
    { id: "p1", name: "Phường Thanh Xuân Bắc" },
    { id: "p2", name: "Phường Thanh Xuân Trung" },
    { id: "p3", name: "Phường Thanh Xuân Nam" },
    { id: "p4", name: "Phường Hạ Đình" },
    { id: "p5", name: "Phường Khương Mai" },
    { id: "p6", name: "Phường Khương Đình" },
    { id: "p7", name: "Phường Khương Thượng" },
    { id: "p8", name: "Phường Tương Mai" },
    { id: "p9", name: "Phường Vĩnh Phúc" },
    { id: "p10", name: "Phường Yên Sơn" },
  ],

  htb: [
    { id: "x1", name: "Xã Thanh Trì" },
    { id: "x2", name: "Xã Hạ Cường" },
    { id: "x3", name: "Xã Thạch Bàn" },
    { id: "x4", name: "Xã Hoài Đức" },
    { id: "x5", name: "Xã Chu Minh" },
    { id: "x6", name: "Xã An Phú" },
    { id: "x7", name: "Xã Dữu Lâu" },
    { id: "x8", name: "Xã Lý Nhạn" },
    { id: "x9", name: "Xã Ân Phú Tây" },
    { id: "x10", name: "Xã Vân Canh" },
    { id: "x11", name: "Xã Lạc Sơn" },
    { id: "x12", name: "Xã Hạ Mỗ" },
  ],

  ph: [
    { id: "x1", name: "Xã Gia Lâm" },
    { id: "x2", name: "Xã Thạch Bàn" },
    { id: "x3", name: "Xã Mỗ Lao" },
    { id: "x4", name: "Xã Hà Kiều" },
    { id: "x5", name: "Xã Đông Dư" },
    { id: "x6", name: "Xã Lâm Sơn" },
    { id: "x7", name: "Xã Liên Phương" },
    { id: "x8", name: "Xã Tân Phú" },
    { id: "x9", name: "Xã Tây Mỗ" },
    { id: "x10", name: "Xã Đông Mỗ" },
    { id: "x11", name: "Xã Vân Hồ" },
    { id: "x12", name: "Xã Lạc Hồng" },
  ],

  sb: [
    { id: "x1", name: "Xã Sóc Sơn" },
    { id: "x2", name: "Xã Phù Liễu" },
    { id: "x3", name: "Xã Ngọc Hồi" },
    { id: "x4", name: "Xã Định Trung" },
    { id: "x5", name: "Xã Tiến Dương" },
    { id: "x6", name: "Xã Xuyên Phương" },
    { id: "x7", name: "Xã Uyên Phương" },
    { id: "x8", name: "Xã Ứng Hòa" },
    { id: "x9", name: "Xã Đại Thắng" },
    { id: "x10", name: "Xã Hùng Sơn" },
    { id: "x11", name: "Xã Quân Sơn" },
    { id: "x12", name: "Xã Tân Dân" },
    { id: "x13", name: "Xã Thanh Sơn" },
  ],

  db: [
    { id: "x1", name: "Xã Đông Anh" },
    { id: "x2", name: "Xã Hồng Hà" },
    { id: "x3", name: "Xã Đông Thư" },
    { id: "x4", name: "Xã Văn Điểm" },
    { id: "x5", name: "Xã Liên Mạc" },
    { id: "x6", name: "Xã Bình Hà" },
    { id: "x7", name: "Xã Quất Động" },
    { id: "x8", name: "Xã Tây Mỗ" },
    { id: "x9", name: "Xã Đông Mỗ" },
    { id: "x10", name: "Xã Vân Sơn" },
    { id: "x11", name: "Xã Tân Triều" },
    { id: "x12", name: "Xã Tiền Phong" },
  ],

  ql: [
    { id: "x1", name: "Xã Quốc Oai" },
    { id: "x2", name: "Xã Hòa Sơn" },
    { id: "x3", name: "Xã Minh Phú" },
    { id: "x4", name: "Xã Phúc Thượng" },
    { id: "x5", name: "Xã Trạm Lộ" },
    { id: "x6", name: "Xã Tây Tựu" },
    { id: "x7", name: "Xã Hòa Phong" },
    { id: "x8", name: "Xã Đại Phúc" },
    { id: "x9", name: "Xã Long Đức" },
    { id: "x10", name: "Xã Hòa Bình" },
    { id: "x11", name: "Xã Tân Dương" },
    { id: "x12", name: "Xã Thạnh An" },
    { id: "x13", name: "Xã Long Sơn" },
  ],

  th: [
    { id: "x1", name: "Xã Thạch Thất" },
    { id: "x2", name: "Xã Bình Yên" },
    { id: "x3", name: "Xã Yên Mỹ" },
    { id: "x4", name: "Xã Đông Dư" },
    { id: "x5", name: "Xã Kim Chúc" },
    { id: "x6", name: "Xã Xuân Phương" },
    { id: "x7", name: "Xã Tân Tựu" },
    { id: "x8", name: "Xã Thượng Mỗ" },
    { id: "x9", name: "Xã Hạ Mỗ" },
    { id: "x10", name: "Xã Tây Mỗ" },
    { id: "x11", name: "Xã Hòa Phong" },
    { id: "x12", name: "Xã Thanh Yên" },
  ],

  ci: [
    { id: "x1", name: "Xã Chương Mỹ" },
    { id: "x2", name: "Xã Phú Cát" },
    { id: "x3", name: "Xã Tân Xã" },
    { id: "x4", name: "Xã Hồi" },
    { id: "x5", name: "Xã Hòa Sơn" },
    { id: "x6", name: "Xã Thái Hà" },
    { id: "x7", name: "Xã Hạ Cường" },
    { id: "x8", name: "Xã Hàng Tây" },
    { id: "x9", name: "Xã Hàng Đông" },
    { id: "x10", name: "Xã Hàng Trung" },
    { id: "x11", name: "Xã Tân Hồng" },
    { id: "x12", name: "Xã Tân Bình" },
  ],

  pp: [
    { id: "x1", name: "Xã Phúc Thọ" },
    { id: "x2", name: "Xã Tây Yên Tử" },
    { id: "x3", name: "Xã Hạ Hoà" },
    { id: "x4", name: "Xã Lương Sơn" },
    { id: "x5", name: "Xã Hữu Hòa" },
    { id: "x6", name: "Xã Bạch Mộc" },
    { id: "x7", name: "Xã Thượng Yên Tử" },
    { id: "x8", name: "Xã Hòa Sơn" },
    { id: "x9", name: "Xã Hòa Lạc" },
    { id: "x10", name: "Xã Tân Phú" },
    { id: "x11", name: "Xã Tân Lâm" },
    { id: "x12", name: "Xã Vân Hồ" },
    { id: "x13", name: "Xã Thanh Sơn" },
  ],

  dd2: [
    { id: "x1", name: "Xã Đan Phương" },
    { id: "x2", name: "Xã Thượng Mỗ" },
    { id: "x3", name: "Xã Hạ Mỗ" },
    { id: "x4", name: "Xã Tây Mỗ" },
    { id: "x5", name: "Xã Luyên Sơn" },
    { id: "x6", name: "Xã Hồng Hà" },
    { id: "x7", name: "Xã Tân Phú" },
    { id: "x8", name: "Xã Tân Lâm" },
    { id: "x9", name: "Xã Vân Sơn" },
    { id: "x10", name: "Xã Long Sơn" },
    { id: "x11", name: "Xã Tân Tiến" },
    { id: "x12", name: "Xã Tân Triều" },
  ],

  mb: [
    { id: "x1", name: "Xã Mỹ Đức" },
    { id: "x2", name: "Xã Tân Xã" },
    { id: "x3", name: "Xã Hồi" },
    { id: "x4", name: "Xã Lạc Sơn" },
    { id: "x5", name: "Xã Đức Mạc" },
    { id: "x6", name: "Xã Tiến Thôn" },
    { id: "x7", name: "Xã Tựu Bình" },
    { id: "x8", name: "Xã Phù Liễu" },
    { id: "x9", name: "Xã Ngọc Hồi" },
    { id: "x10", name: "Xã Định Trung" },
    { id: "x11", name: "Xã Tiến Dương" },
    { id: "x12", name: "Xã Xuyên Phương" },
    { id: "x13", name: "Xã Uyên Phương" },
  ],

  // ======================== TP. HỒ CHÍ MINH (24 quận/huyện) ========================
  q1: [
    { id: "p1", name: "Phường Bến Nghé" },
    { id: "p2", name: "Phường Bến Thành" },
    { id: "p3", name: "Phường Đa Kao" },
    { id: "p4", name: "Phường Nguyễn Hữu Cảnh" },
    { id: "p5", name: "Phường Tân Định" },
    { id: "p6", name: "Phường Tây Kinh" },
    { id: "p7", name: "Phường Cầu Kho" },
    { id: "p8", name: "Phường Cầu Ông Lãnh" },
  ],

  q2: [
    { id: "p1", name: "Phường An Lạc" },
    { id: "p2", name: "Phường An Khánh" },
    { id: "p3", name: "Phường Bình An" },
    { id: "p4", name: "Phường Thảo Điền" },
    { id: "p5", name: "Phường Cát Lái" },
    { id: "p6", name: "Phường Tân Phú" },
    { id: "p7", name: "Phường Bình Trưng Đông" },
    { id: "p8", name: "Phường Bình Trưng Tây" },
    { id: "p9", name: "Phường An Phú" },
  ],

  q3: [
    { id: "p1", name: "Phường 1" },
    { id: "p2", name: "Phường 2" },
    { id: "p3", name: "Phường 3" },
    { id: "p4", name: "Phường 4" },
    { id: "p5", name: "Phường 5" },
    { id: "p6", name: "Phường 6" },
    { id: "p7", name: "Phường 7" },
    { id: "p8", name: "Phường 8" },
    { id: "p9", name: "Phường 9" },
    { id: "p10", name: "Phường 10" },
    { id: "p11", name: "Phường 11" },
    { id: "p12", name: "Phường 12" },
    { id: "p13", name: "Phường 13" },
  ],

  q4: [
    { id: "p1", name: "Phường 1" },
    { id: "p2", name: "Phường 2" },
    { id: "p3", name: "Phường 3" },
    { id: "p4", name: "Phường 4" },
    { id: "p5", name: "Phường 5" },
    { id: "p6", name: "Phường 6" },
    { id: "p7", name: "Phường 7" },
    { id: "p8", name: "Phường 8" },
    { id: "p9", name: "Phường 9" },
    { id: "p10", name: "Phường 10" },
  ],

  q5: [
    { id: "p1", name: "Phường 1" },
    { id: "p2", name: "Phường 2" },
    { id: "p3", name: "Phường 3" },
    { id: "p4", name: "Phường 4" },
    { id: "p5", name: "Phường 5" },
    { id: "p6", name: "Phường 6" },
    { id: "p7", name: "Phường 7" },
    { id: "p8", name: "Phường 8" },
    { id: "p9", name: "Phường 9" },
    { id: "p10", name: "Phường 10" },
    { id: "p11", name: "Phường 11" },
    { id: "p12", name: "Phường 12" },
  ],

  q6: [
    { id: "p1", name: "Phường 1" },
    { id: "p2", name: "Phường 2" },
    { id: "p3", name: "Phường 3" },
    { id: "p4", name: "Phường 4" },
    { id: "p5", name: "Phường 5" },
    { id: "p6", name: "Phường 6" },
    { id: "p7", name: "Phường 7" },
    { id: "p8", name: "Phường 8" },
    { id: "p9", name: "Phường 9" },
    { id: "p10", name: "Phường 10" },
  ],

  q7: [
    { id: "p1", name: "Phường 1" },
    { id: "p2", name: "Phường 2" },
    { id: "p3", name: "Phường 3" },
    { id: "p4", name: "Phường 4" },
    { id: "p5", name: "Phường 5" },
    { id: "p6", name: "Phường 6" },
    { id: "p7", name: "Phường 7" },
    { id: "p8", name: "Phường 8" },
    { id: "p9", name: "Phường 9" },
    { id: "p10", name: "Phường 10" },
    { id: "p11", name: "Phường 11" },
    { id: "p12", name: "Phường 12" },
  ],

  q8: [
    { id: "p1", name: "Phường 1" },
    { id: "p2", name: "Phường 2" },
    { id: "p3", name: "Phường 3" },
    { id: "p4", name: "Phường 4" },
    { id: "p5", name: "Phường 5" },
    { id: "p6", name: "Phường 6" },
    { id: "p7", name: "Phường 7" },
    { id: "p8", name: "Phường 8" },
    { id: "p9", name: "Phường 9" },
    { id: "p10", name: "Phường 10" },
    { id: "p11", name: "Phường 11" },
  ],

  q9: [
    { id: "p1", name: "Phường 1" },
    { id: "p2", name: "Phường 2" },
    { id: "p3", name: "Phường 3" },
    { id: "p4", name: "Phường 4" },
    { id: "p5", name: "Phường 5" },
    { id: "p6", name: "Phường 6" },
    { id: "p7", name: "Phường 7" },
    { id: "p8", name: "Phường 8" },
    { id: "p9", name: "Phường 9" },
    { id: "p10", name: "Phường 10" },
  ],

  q10: [
    { id: "p1", name: "Phường 1" },
    { id: "p2", name: "Phường 2" },
    { id: "p3", name: "Phường 3" },
    { id: "p4", name: "Phường 4" },
    { id: "p5", name: "Phường 5" },
    { id: "p6", name: "Phường 6" },
    { id: "p7", name: "Phường 7" },
    { id: "p8", name: "Phường 8" },
    { id: "p9", name: "Phường 9" },
  ],

  q11: [
    { id: "p1", name: "Phường 1" },
    { id: "p2", name: "Phường 2" },
    { id: "p3", name: "Phường 3" },
    { id: "p4", name: "Phường 4" },
    { id: "p5", name: "Phường 5" },
    { id: "p6", name: "Phường 6" },
    { id: "p7", name: "Phường 7" },
    { id: "p8", name: "Phường 8" },
    { id: "p9", name: "Phường 9" },
    { id: "p10", name: "Phường 10" },
    { id: "p11", name: "Phường 11" },
    { id: "p12", name: "Phường 12" },
  ],

  q12: [
    { id: "p1", name: "Phường 1" },
    { id: "p2", name: "Phường 2" },
    { id: "p3", name: "Phường 3" },
    { id: "p4", name: "Phường 4" },
    { id: "p5", name: "Phường 5" },
    { id: "p6", name: "Phường 6" },
    { id: "p7", name: "Phường 7" },
    { id: "p8", name: "Phường 8" },
    { id: "p9", name: "Phường 9" },
  ],

  tbu: [
    { id: "p1", name: "Phường Tân Bình" },
    { id: "p2", name: "Phường Sơn Kỳ" },
    { id: "p3", name: "Phường Tây Thạnh" },
    { id: "p4", name: "Phường Tây Hòa" },
    { id: "p5", name: "Phường Phú Thạnh" },
    { id: "p6", name: "Phường Tân Tạo" },
    { id: "p7", name: "Phường Tân Phú" },
    { id: "p8", name: "Phường Tân Thòi Nhất" },
  ],

  tph: [
    { id: "p1", name: "Phường Tân Phú" },
    { id: "p2", name: "Phường Sơn Kỳ" },
    { id: "p3", name: "Phường Tây Thạnh" },
    { id: "p4", name: "Phường Tân Thới Hòa" },
    { id: "p5", name: "Phường Tân Thới Nhất" },
    { id: "p6", name: "Phường Tây Hòa" },
    { id: "p7", name: "Phường Hòa Thạnh" },
    { id: "p8", name: "Phường Hòa Lạc" },
    { id: "p9", name: "Phường Phú Thạnh" },
  ],

  gv: [
    { id: "p1", name: "Phường Phú Thạnh" },
    { id: "p2", name: "Phường Phú Thọ Hòa" },
    { id: "p3", name: "Phường Phú Nhuận" },
    { id: "p4", name: "Phường Trung Mỹ Tây" },
    { id: "p5", name: "Phường Trung Cộng" },
    { id: "p6", name: "Phường Thạnh Lộc" },
    { id: "p7", name: "Phường Thạnh Xuân" },
    { id: "p8", name: "Phường Trung Mỹ Bắc" },
  ],

  bt: [
    { id: "p1", name: "Phường 1" },
    { id: "p2", name: "Phường 2" },
    { id: "p3", name: "Phường 3" },
    { id: "p4", name: "Phường 4" },
    { id: "p5", name: "Phường 5" },
    { id: "p6", name: "Phường 6" },
    { id: "p7", name: "Phường 7" },
    { id: "p8", name: "Phường 8" },
  ],

  bta: [
    { id: "p1", name: "Phường An Lạc" },
    { id: "p2", name: "Phường An Nhơn" },
    { id: "p3", name: "Phường Bình Hưng Hòa" },
    { id: "p4", name: "Phường Bình Hưng Hòa A" },
    { id: "p5", name: "Phường Bình Hưng Hòa B" },
    { id: "p6", name: "Phường Tân Tạo" },
    { id: "p7", name: "Phường Tân Tạo A" },
    { id: "p8", name: "Phường Tân Hóa" },
    { id: "p9", name: "Phường Tân Hòa Đông" },
  ],

  cc: [
    { id: "x1", name: "Xã Tân Phúc" },
    { id: "x2", name: "Xã Tân Thới Nhất" },
    { id: "x3", name: "Xã An Phú" },
    { id: "x4", name: "Xã Tân Túc" },
    { id: "x5", name: "Xã Hòa Phú" },
    { id: "x6", name: "Xã Phước Hiệp" },
    { id: "x7", name: "Xã Phước Thạnh" },
    { id: "x8", name: "Xã Tân Lập" },
    { id: "x9", name: "Xã Hòa Thạnh" },
    { id: "x10", name: "Xã Hòa Lạc" },
  ],

  hm2: [
    { id: "x1", name: "Xã Tân Xuân" },
    { id: "x2", name: "Xã Nhị Bình" },
    { id: "x3", name: "Xã Tân Kiểng" },
    { id: "x4", name: "Xã Bà Điểm" },
    { id: "x5", name: "Xã Trung Cộng" },
    { id: "x6", name: "Xã Tân Thạnh" },
    { id: "x7", name: "Xã Nhuận Đức" },
    { id: "x8", name: "Xã Đông Thạnh" },
    { id: "x9", name: "Xã Tân Lập" },
  ],

  nb: [
    { id: "x1", name: "Xã Nhà Bè" },
    { id: "x2", name: "Xã An Phú" },
    { id: "x3", name: "Xã Long Thới" },
    { id: "x4", name: "Xã Hiệp Phú" },
    { id: "x5", name: "Xã Phong Phú" },
    { id: "x6", name: "Xã Phú Xuân" },
    { id: "x7", name: "Xã Long Bình Tân" },
  ],

  cg2: [
    { id: "x1", name: "Xã Cần Giờ" },
    { id: "x2", name: "Xã Lý Sơn" },
    { id: "x3", name: "Xã Thạnh An" },
    { id: "x4", name: "Xã Tam Thôn Hiệp" },
    { id: "x5", name: "Xã An Thới Đông" },
    { id: "x6", name: "Xã An Thới Tây" },
  ],

  // ======================== ĐÀ NẴNG (6 quận/huyện) ========================
  hc: [
    { id: "p1", name: "Phường Hải Châu I" },
    { id: "p2", name: "Phường Hải Châu II" },
    { id: "p3", name: "Phường Thanh Bình" },
    { id: "p4", name: "Phường Thạch Thang" },
    { id: "p5", name: "Phường Hòa Cương Bắc" },
    { id: "p6", name: "Phường Hòa Cương Nam" },
    { id: "p7", name: "Phường Bắc Mỹ An" },
    { id: "p8", name: "Phường Hòa An" },
  ],

  thk: [
    { id: "p1", name: "Phường Thanh Khe Tây" },
    { id: "p2", name: "Phường Thanh Khe Đông" },
    { id: "p3", name: "Phường Tân Chính" },
    { id: "p4", name: "Phường Vĩnh Trung" },
    { id: "p5", name: "Phường Vĩnh Trực" },
    { id: "p6", name: "Phường Bình Hiên" },
    { id: "p7", name: "Phường Vĩnh Hòa" },
  ],

  st: [
    { id: "p1", name: "Phường Mỹ An" },
    { id: "p2", name: "Phường Nại Hiên Đông" },
    { id: "p3", name: "Phường Phước Mỹ" },
    { id: "p4", name: "Phường An Hải Bắc" },
    { id: "p5", name: "Phường An Hải Tây" },
    { id: "p6", name: "Phường Thọ Quang" },
    { id: "p7", name: "Phường Nước Ngọt" },
    { id: "p8", name: "Phường Khuê Trung" },
  ],

  cl: [
    { id: "p1", name: "Phường Cẩm Lệ" },
    { id: "p2", name: "Phường Hòa Khánh Nam" },
    { id: "p3", name: "Phường Hòa Khánh Bắc" },
    { id: "p4", name: "Phường Khuê Trung" },
    { id: "p5", name: "Phường Cam Lộ" },
  ],

  nhs: [
    { id: "x1", name: "Xã Ngũ Hành Sơn" },
    { id: "x2", name: "Xã Mỹ Khê" },
    { id: "x3", name: "Xã Mỹ An" },
    { id: "x4", name: "Xã Mân Thái" },
    { id: "x5", name: "Xã Hòa Phong" },
    { id: "x6", name: "Xã Hòa Bình" },
  ],

  lc: [
    { id: "x1", name: "Xã Liên Chiểu" },
    { id: "x2", name: "Xã Hòa Hiệp Nam" },
    { id: "x3", name: "Xã Hòa Hiệp Bắc" },
    { id: "x4", name: "Xã Hòa Phương" },
    { id: "x5", name: "Xã Hòa Lạc" },
  ],

  hv: [
    { id: "x1", name: "Xã Hòa Vang" },
    { id: "x2", name: "Xã Hòa Ninh" },
    { id: "x3", name: "Xã Hòa Bắc" },
    { id: "x4", name: "Xã Hòa Phú" },
    { id: "x5", name: "Xã Hòa Sơn" },
    { id: "x6", name: "Xã Hòa Khương" },
    { id: "x7", name: "Xã Hòa Tiến" },
    { id: "x8", name: "Xã Hòa Tân" },
  ],

  // ======================== HẢI PHÒNG (5 quận) ========================
  hb: [
    { id: "p1", name: "Phường Hồng Bàng" },
    { id: "p2", name: "Phường Cát Dài" },
    { id: "p3", name: "Phường Quán Toan" },
    { id: "p4", name: "Phường Máy Tơ" },
    { id: "p5", name: "Phường Trại Cau" },
    { id: "p6", name: "Phường Ngô Thị Nhậm" },
    { id: "p7", name: "Phường Bạch Mã" },
    { id: "p8", name: "Phường Đống Dương" },
    { id: "p9", name: "Phường Đại Minh" },
    { id: "p10", name: "Phường Hiệp Hòa" },
    { id: "p11", name: "Phường Vạn Phúc" },
    { id: "p12", name: "Phường Tức Dục" },
    { id: "p13", name: "Phường Lạch Tray" },
  ],

  nq: [
    { id: "p1", name: "Phường Ngô Quyền" },
    { id: "p2", name: "Phường Lạch Tray" },
    { id: "p3", name: "Phường Trần Phú" },
    { id: "p4", name: "Phường Hoàng Văn Thụ" },
    { id: "p5", name: "Phường Minh Khai" },
    { id: "p6", name: "Phường Hạ Lý" },
    { id: "p7", name: "Phường Cái Dầu" },
    { id: "p8", name: "Phường Vân Đồn" },
    { id: "p9", name: "Phường Cát Bi" },
    { id: "p10", name: "Phường Thuỵ An" },
    { id: "p11", name: "Phường Dương Lâm" },
    { id: "p12", name: "Phường Khánh Bình" },
  ],

  lch: [
    { id: "p1", name: "Phường Lê Chân" },
    { id: "p2", name: "Phường Khánh Bình" },
    { id: "p3", name: "Phường Cát Bi" },
    { id: "p4", name: "Phường Dương Lâm" },
    { id: "p5", name: "Phường Hạ Lý" },
    { id: "p6", name: "Phường Phà Rhai" },
    { id: "p7", name: "Phường Đặng Leng" },
    { id: "p8", name: "Phường Bạch Đằng" },
    { id: "p9", name: "Phường Thiên Quang" },
    { id: "p10", name: "Phường Thạch Hà" },
    { id: "p11", name: "Phường Nhân Hòa" },
    { id: "p12", name: "Phường Hồng Gai" },
  ],

  ka: [
    { id: "p1", name: "Phường Kiến An" },
    { id: "p2", name: "Phường Tây Hồ" },
    { id: "p3", name: "Phường Thái Phiên" },
    { id: "p4", name: "Phường Yên Phụ" },
    { id: "p5", name: "Phường Hồng Bàng" },
    { id: "p6", name: "Phường Trại Cau" },
    { id: "p7", name: "Phường Dịch Tân" },
    { id: "p8", name: "Phường Hữu Quyền" },
    { id: "p9", name: "Phường Lam Sơn" },
    { id: "p10", name: "Phường Thới Hòa" },
    { id: "p11", name: "Phường Vạn Phúc" },
  ],

  thh: [
    { id: "p1", name: "Phường Tây Hồ" },
    { id: "p2", name: "Phường Đông Khê" },
    { id: "p3", name: "Phường An Dương" },
    { id: "p4", name: "Phường Niệm Nghĩa" },
    { id: "p5", name: "Phường Vân Đồn" },
    { id: "p6", name: "Phường Cát Bi" },
    { id: "p7", name: "Phường Mạo Khê" },
    { id: "p8", name: "Phường Dịch Tân" },
  ],

  // ======================== CẦN THƠ (4 quận) ========================
  nk: [
    { id: "p1", name: "Phường Ninh Kiều" },
    { id: "p2", name: "Phường Cái Khế" },
    { id: "p3", name: "Phường An Phú" },
    { id: "p4", name: "Phường An Khánh" },
    { id: "p5", name: "Phường Xuân Khánh" },
    { id: "p6", name: "Phường Hưng Lợi" },
    { id: "p7", name: "Phường Cái Khế" },
    { id: "p8", name: "Phường Tân Phú" },
    { id: "p9", name: "Phường Hồng Mỹ" },
    { id: "p10", name: "Phường Bình Thủy" },
    { id: "p11", name: "Phường Trí Nữ" },
    { id: "p12", name: "Phường Long Tuyền" },
    { id: "p13", name: "Phường Quới Đốc" },
  ],

  om: [
    { id: "p1", name: "Phường Ô Môn" },
    { id: "p2", name: "Phường An Hòa" },
    { id: "p3", name: "Phường Trường Thạnh" },
    { id: "p4", name: "Phường Tân Phú" },
    { id: "p5", name: "Phường Thuận An" },
    { id: "p6", name: "Phường Hồng Nhan" },
    { id: "p7", name: "Phường Mỹ Khánh" },
    { id: "p8", name: "Phường Tân Thạnh" },
    { id: "p9", name: "Phường Thạnh Mỹ Lợi" },
    { id: "p10", name: "Phường Vĩnh Thạnh" },
    { id: "p11", name: "Phường Châu Văn Liêm" },
  ],

  tn: [
    { id: "p1", name: "Phường Thốt Nốt" },
    { id: "p2", name: "Phường Xuân Phú" },
    { id: "p3", name: "Phường Tân Phú" },
    { id: "p4", name: "Phường Châu Văn Liêm" },
    { id: "p5", name: "Phường Quới Sơn" },
    { id: "p6", name: "Phường Hồng Nhan" },
    { id: "p7", name: "Phường Mỹ Khánh" },
    { id: "p8", name: "Phường Tân Thạnh" },
    { id: "p9", name: "Phường Thạnh Mỹ Lợi" },
    { id: "p10", name: "Phường Vĩnh Thạnh" },
    { id: "p11", name: "Phường Long Tuyền" },
  ],

  cr: [
    { id: "p1", name: "Phường Cái Răng" },
    { id: "p2", name: "Phường Hưng Phú" },
    { id: "p3", name: "Phường Trần Phú" },
    { id: "p4", name: "Phường Tân Lợi" },
    { id: "p5", name: "Phường Xuân Khánh" },
    { id: "p6", name: "Phường Bình Thủy" },
    { id: "p7", name: "Phường Mỹ Bình" },
    { id: "p8", name: "Phường Tân Phú" },
    { id: "p9", name: "Phường Hồng Mỹ" },
    { id: "p10", name: "Phường Thạnh Mỹ Lợi" },
    { id: "p11", name: "Phường Trí Nữ" },
    { id: "p12", name: "Phường Long Tuyền" },
    { id: "p13", name: "Phường Quới Đốc" },
  ],

  // ======================== AN GIANG (8 quận/huyện) ========================
  lt: [
    { id: "p1", name: "Phường Bình Tân" },
    { id: "p2", name: "Phường Bình Mỹ" },
    { id: "p3", name: "Phường Mỹ Bình" },
    { id: "p4", name: "Phường Mỹ Xuyên" },
    { id: "p5", name: "Phường Tân Phú" },
    { id: "p6", name: "Phường Bình Khê" },
    { id: "p7", name: "Phường An Phú" },
    { id: "p8", name: "Phường Vĩnh Tế" },
    { id: "p9", name: "Phường Mỹ Hòa" },
    { id: "p10", name: "Phường Bình Hòa" },
    { id: "p11", name: "Phường Bình Phú" },
    { id: "p12", name: "Phường Bình Hưng" },
  ],

  cd: [
    { id: "p1", name: "Phường Châu Đốc" },
    { id: "p2", name: "Phường Mỹ Long" },
    { id: "p3", name: "Phường Mỹ Phước" },
    { id: "p4", name: "Phường Khánh Bình" },
    { id: "p5", name: "Phường Tân Phú" },
    { id: "p6", name: "Phường Nhơn Phú" },
    { id: "p7", name: "Phường Châu Phú" },
    { id: "p8", name: "Phường Thanh Bình" },
    { id: "p9", name: "Phường Bình Khê" },
    { id: "p10", name: "Phường Khánh An" },
  ],

  chm: [
    { id: "x1", name: "Xã Chợ Mới" },
    { id: "x2", name: "Xã An Khánh" },
    { id: "x3", name: "Xã Vĩnh Hòa" },
    { id: "x4", name: "Xã Hòa Mỹ" },
    { id: "x5", name: "Xã Bắc Mỹ" },
    { id: "x6", name: "Xã Tân Hòa" },
    { id: "x7", name: "Xã Tân Lập" },
    { id: "x8", name: "Xã Tân Tiến" },
    { id: "x9", name: "Xã Tân Trụ" },
    { id: "x10", name: "Xã Long Hòa" },
    { id: "x11", name: "Xã Bình Tân" },
    { id: "x12", name: "Xã Thiên Hương" },
    { id: "x13", name: "Xã Tân Phú" },
  ],

  tb: [
    { id: "x1", name: "Xã Tịnh Biên" },
    { id: "x2", name: "Xã Tân Quy" },
    { id: "x3", name: "Xã Tân Phú" },
    { id: "x4", name: "Xã Hòa Lạc" },
    { id: "x5", name: "Xã Bắc Mỹ" },
    { id: "x6", name: "Xã Tân Hòa" },
    { id: "x7", name: "Xã Tân Lập" },
    { id: "x8", name: "Xã Long Hòa" },
    { id: "x9", name: "Xã Bình Tân" },
    { id: "x10", name: "Xã Vĩnh Tế" },
    { id: "x11", name: "Xã Tân Tiến" },
    { id: "x12", name: "Xã Thiên Hương" },
  ],

  pt_ag: [
    { id: "x1", name: "Xã Phú Tân" },
    { id: "x2", name: "Xã Phú Miễn" },
    { id: "x3", name: "Xã Phú Mỹ" },
    { id: "x4", name: "Xã Tân Lập" },
    { id: "x5", name: "Xã Bắc Mỹ" },
    { id: "x6", name: "Xã Tân Hòa" },
    { id: "x7", name: "Xã Hòa Lạc" },
    { id: "x8", name: "Xã Tân Tiến" },
    { id: "x9", name: "Xã Long Hòa" },
    { id: "x10", name: "Xã Bình Tân" },
    { id: "x11", name: "Xã Vĩnh Tế" },
    { id: "x12", name: "Xã Thiên Hương" },
    { id: "x13", name: "Xã Tân Phú" },
  ],

  ap: [
    { id: "x1", name: "Xã An Phú" },
    { id: "x2", name: "Xã Tân Trụ" },
    { id: "x3", name: "Xã Vĩnh Thanh" },
    { id: "x4", name: "Xã Hòa Bình" },
    { id: "x5", name: "Xã Bắc Mỹ" },
    { id: "x6", name: "Xã Tân Hòa" },
    { id: "x7", name: "Xã Tân Lập" },
    { id: "x8", name: "Xã Long Hòa" },
    { id: "x9", name: "Xã Bình Tân" },
    { id: "x10", name: "Xã Vĩnh Tế" },
    { id: "x11", name: "Xã Tân Tiến" },
    { id: "x12", name: "Xã Thiên Hương" },
  ],

  cp: [
    { id: "x1", name: "Xã Châu Phú" },
    { id: "x2", name: "Xã Vĩnh Trung" },
    { id: "x3", name: "Xã An Tĩnh" },
    { id: "x4", name: "Xã Tân Châu" },
    { id: "x5", name: "Xã Tân Hòa" },
    { id: "x6", name: "Xã Tân Lập" },
    { id: "x7", name: "Xã Hòa Bình" },
    { id: "x8", name: "Xã Bắc Mỹ" },
    { id: "x9", name: "Xã Long Hòa" },
    { id: "x10", name: "Xã Vĩnh Tế" },
    { id: "x11", name: "Xã Tân Tiến" },
  ],

  ch: [
    { id: "x1", name: "Xã Chợ Chùa" },
    { id: "x2", name: "Xã Tân Tiến" },
    { id: "x3", name: "Xã Tân Lập" },
    { id: "x4", name: "Xã Bắc Mỹ" },
    { id: "x5", name: "Xã Hòa Bình" },
    { id: "x6", name: "Xã Tân Hòa" },
    { id: "x7", name: "Xã Long Hòa" },
    { id: "x8", name: "Xã Vĩnh Hòa" },
    { id: "x9", name: "Xã Thanh Bình" },
    { id: "x10", name: "Xã Vĩnh Tế" },
  ],

  // ======================== BẮC GIANG (TP Bắc Giang) ========================
  bg: [
    { id: "p1", name: "Phường Tân Nguyên" },
    { id: "p2", name: "Phường Trần Hưng Đạo" },
    { id: "p3", name: "Phường Michelin" },
    { id: "p4", name: "Phường Tân Tố" },
    { id: "p5", name: "Phường Lục Nạn" },
    { id: "p6", name: "Phường Dương Kinh" },
    { id: "p7", name: "Phường Yên Thế" },
    { id: "p8", name: "Phường Nam Phong" },
    { id: "p9", name: "Phường Xuân Canh" },
    { id: "p10", name: "Phường Yên Sơn" },
    { id: "p11", name: "Phường Yên Phú" },
    { id: "p12", name: "Phường Niên Tôn" },
  ],
  // Huyện Lạng Giang
  lg_bg: [
    { id: "x1", name: "Xã Mỹ Hưng" },
    { id: "x2", name: "Xã Xuân Canh" },
    { id: "x3", name: "Xã Hạp Lị" },
    { id: "x4", name: "Xã Minh Tân" },
    { id: "x5", name: "Xã Liễu Chỉ" },
    { id: "x6", name: "Xã Thanh Tân" },
    { id: "x7", name: "Xã Mộc Châu" },
    { id: "x8", name: "Xã Hoàng Lợi" },
    { id: "x9", name: "Xã Dân Phương" },
    { id: "x10", name: "Xã Quyết Thắng" },
    { id: "x11", name: "Xã Hòa Bình" },
    { id: "x12", name: "Xã Nhân Hòa" },
  ],
  // Huyện Yên Thế
  yt_bg: [
    { id: "x1", name: "Xã Hùng Sơn" },
    { id: "x2", name: "Xã Đồng Bẩu" },
    { id: "x3", name: "Xã Tân Thanh" },
    { id: "x4", name: "Xã Hùng Thắng" },
    { id: "x5", name: "Xã Tân Lập" },
    { id: "x6", name: "Xã Hàng Trung" },
    { id: "x7", name: "Xã Hàng Gai" },
    { id: "x8", name: "Xã Gia Quân" },
    { id: "x9", name: "Xã Liên Hòa" },
    { id: "x10", name: "Xã Quốc Tuấn" },
    { id: "x11", name: "Xã Tân Hợp" },
  ],
  // Huyện Tân Yên
  ty_bg: [
    { id: "x1", name: "Xã Tân Yên" },
    { id: "x2", name: "Xã Hiệp Hòa" },
    { id: "x3", name: "Xã Mỹ Khê" },
    { id: "x4", name: "Xã Bảo Liên" },
    { id: "x5", name: "Xã Hồng Hà" },
    { id: "x6", name: "Xã Tân Bình" },
    { id: "x7", name: "Xã Đại Thắng" },
    { id: "x8", name: "Xã Đại Phong" },
    { id: "x9", name: "Xã Bảo Hòa" },
    { id: "x10", name: "Xã Song Hồ" },
  ],
  // Huyện Việt Yên
  vy_bg: [
    { id: "x1", name: "Xã Việt Yên" },
    { id: "x2", name: "Xã Quốc Thái" },
    { id: "x3", name: "Xã Hùng Lợi" },
    { id: "x4", name: "Xã Tân Phương" },
    { id: "x5", name: "Xã Long Sơn" },
    { id: "x6", name: "Xã Quốc Hương" },
    { id: "x7", name: "Xã Tân Hồng" },
    { id: "x8", name: "Xã Bảo Hiệp" },
    { id: "x9", name: "Xã Phú Tiến" },
    { id: "x10", name: "Xã Quý Tân" },
    { id: "x11", name: "Xã Tạo Phương" },
  ],

  // ======================== BẮC KẠN (TP Bắc Kạn) ========================
  bk: [
    { id: "p1", name: "Phường Nông Cống" },
    { id: "p2", name: "Phường Việt Đức" },
    { id: "p3", name: "Phường Bình An" },
    { id: "p4", name: "Phường Pác Cà" },
    { id: "p5", name: "Phường Lục Quy" },
    { id: "p6", name: "Phường Yên Bình" },
    { id: "p7", name: "Phường Tân Hòa" },
    { id: "p8", name: "Phường Tân Mỹ" },
    { id: "p9", name: "Phường Trung Hòa" },
    { id: "p10", name: "Phường Tam Sơn" },
    { id: "p11", name: "Phường Phú Lương" },
    { id: "p12", name: "Phường Thiên Hòa" },
  ],
  // Huyện Bắc Kạn
  bk_hc: [
    { id: "x1", name: "Xã Lục Quy" },
    { id: "x2", name: "Xã Minh Tiến" },
    { id: "x3", name: "Xã Hiệp Hòa" },
    { id: "x4", name: "Xã Sơn Sơn" },
    { id: "x5", name: "Xã Tân An" },
    { id: "x6", name: "Xã Phú Lương" },
    { id: "x7", name: "Xã Hiệp Khánh" },
    { id: "x8", name: "Xã Quảng Hòa" },
    { id: "x9", name: "Xã Tân Lập" },
    { id: "x10", name: "Xã Long Hòa" },
    { id: "x11", name: "Xã Trường Sơn" },
  ],
  // Huyện Ba Bể
  bb: [
    { id: "x1", name: "Xã Ba Bể" },
    { id: "x2", name: "Xã Pác Nai" },
    { id: "x3", name: "Xã Pác Khuôn" },
    { id: "x4", name: "Xã Hòa An" },
    { id: "x5", name: "Xã Đôi Ngoại" },
    { id: "x6", name: "Xã Phúc Sơn" },
    { id: "x7", name: "Xã Hùng Phương" },
    { id: "x8", name: "Xã Thanh Hòa" },
    { id: "x9", name: "Xã Tân Thắng" },
    { id: "x10", name: "Xã Mỹ Khê" },
  ],
  // Huyện Chợ Đồn
  cd_bk: [
    { id: "x1", name: "Xã Chợ Đồn" },
    { id: "x2", name: "Xã Hùng Hà" },
    { id: "x3", name: "Xã Tân Hạnh" },
    { id: "x4", name: "Xã Hiệp Hương" },
    { id: "x5", name: "Xã Thanh Minh" },
    { id: "x6", name: "Xã Phúc Hòa" },
    { id: "x7", name: "Xã Hoa Sơn" },
    { id: "x8", name: "Xã Hương Sơn" },
  ],
  // Huyện Thái Nguyên
  tng: [
    { id: "x1", name: "Xã Tân Hương" },
    { id: "x2", name: "Xã Quảng Hòa" },
    { id: "x3", name: "Xã Đôi Sơn" },
    { id: "x4", name: "Xã Quang Lâm" },
    { id: "x5", name: "Xã Tân Thắng" },
    { id: "x6", name: "Xã Hùng Sơn" },
    { id: "x7", name: "Xã Đông An" },
    { id: "x8", name: "Xã Long Thành" },
    { id: "x9", name: "Xã Hợp Hòa" },
    { id: "x10", name: "Xã Phú Nhuận" },
  ],

  // ======================== BẠC LIÊU (TP Bạc Liêu) ========================
  bl: [
    { id: "p1", name: "Phường 1" },
    { id: "p2", name: "Phường 2" },
    { id: "p3", name: "Phường 3" },
    { id: "p4", name: "Phường 4" },
    { id: "p5", name: "Phường 5" },
    { id: "p6", name: "Phường 6" },
    { id: "p7", name: "Phường Nông Trang" },
    { id: "p8", name: "Phường Cái Dăm" },
    { id: "p9", name: "Phường Tân An" },
    { id: "p10", name: "Phường Vĩnh Hòa" },
    { id: "p11", name: "Phường Mỹ Xuyên" },
    { id: "p12", name: "Phường Duyên Hải" },
  ],
  // Huyện Bạc Liêu
  bl_hc: [
    { id: "x1", name: "Xã Bạc Liêu" },
    { id: "x2", name: "Xã Tân Thạnh" },
    { id: "x3", name: "Xã Tân Lập" },
    { id: "x4", name: "Xã Hồng Dân" },
    { id: "x5", name: "Xã Khánh Hòa" },
    { id: "x6", name: "Xã Thạnh Tân" },
    { id: "x7", name: "Xã Tân Uyên" },
    { id: "x8", name: "Xã Phước Long" },
    { id: "x9", name: "Xã Mỹ Khánh" },
    { id: "x10", name: "Xã Thanh Bình" },
    { id: "x11", name: "Xã Trí Tân" },
  ],
  // Huyện Hòa Bình
  hb_bl: [
    { id: "x1", name: "Xã Hòa Bình" },
    { id: "x2", name: "Xã Huyền Duy" },
    { id: "x3", name: "Xã Tân Phước" },
    { id: "x4", name: "Xã Tân Hòa" },
    { id: "x5", name: "Xã Phước Hòa" },
    { id: "x6", name: "Xã Thạnh Hòa" },
    { id: "x7", name: "Xã Mỹ Tân" },
    { id: "x8", name: "Xã Vĩnh Hòa" },
    { id: "x9", name: "Xã Tân Mỹ" },
  ],

  // ======================== BẮC NINH (TP Bắc Ninh) ========================
  bn: [
    { id: "p1", name: "Phường Suối Hoa" },
    { id: "p2", name: "Phường Phù Gia" },
    { id: "p3", name: "Phường Hải Hà" },
    { id: "p4", name: "Phường Tiên Du" },
    { id: "p5", name: "Phường Ngô Quyền" },
    { id: "p6", name: "Phường Tây Vu" },
    { id: "p7", name: "Phường Phú Thịnh" },
    { id: "p8", name: "Phường Tân Bình" },
    { id: "p9", name: "Phường Yên Phong" },
    { id: "p10", name: "Phường Kinh Bắc" },
    { id: "p11", name: "Phường Phúc Toàn" },
    { id: "p12", name: "Phường Tân Thắng" },
  ],
  // Huyện Bắc Ninh
  bn_hc: [
    { id: "x1", name: "Xã Hạp Lị" },
    { id: "x2", name: "Xã Tân Thắng" },
    { id: "x3", name: "Xã Tân Lập" },
    { id: "x4", name: "Xã Tân Hòa" },
    { id: "x5", name: "Xã Thanh Hòa" },
    { id: "x6", name: "Xã Yên Tâm" },
    { id: "x7", name: "Xã Song Phương" },
    { id: "x8", name: "Xã Thuận Tân" },
    { id: "x9", name: "Xã Lương Tài" },
    { id: "x10", name: "Xã Hiệp Hòa" },
    { id: "x11", name: "Xã Tiên Hòa" },
  ],
  // Huyện Yên Phong
  yp_bn: [
    { id: "x1", name: "Xã Yên Phong" },
    { id: "x2", name: "Xã Tân Tây" },
    { id: "x3", name: "Xã Thanh Phương" },
    { id: "x4", name: "Xã Tân Hòa" },
    { id: "x5", name: "Xã Tân Lập" },
    { id: "x6", name: "Xã Long Sơn" },
    { id: "x7", name: "Xã Yên Tâm" },
    { id: "x8", name: "Xã Tân Dân" },
    { id: "x9", name: "Xã Thanh Tân" },
    { id: "x10", name: "Xã Tân Minh" },
  ],

  // ======================== BÌNH PHƯỚC (TP Đồng Xoài) ========================
  dx: [
    { id: "p1", name: "Phường Phước Bình" },
    { id: "p2", name: "Phường Tân Bình" },
    { id: "p3", name: "Phường Tân Hiệp" },
    { id: "p4", name: "Phường Tân Thanh" },
    { id: "p5", name: "Phường Dương Quang" },
    { id: "p6", name: "Phường Tân Quang" },
    { id: "p7", name: "Phường Bến Cát" },
    { id: "p8", name: "Phường Tân Chính" },
    { id: "p9", name: "Phường Hương Sơn" },
    { id: "p10", name: "Phường Tam Lộc" },
    { id: "p11", name: "Phường Phú Riềng" },
    { id: "p12", name: "Phường Phú Hòa" },
  ],
  // Huyện Bù Đắp
  bd_bp: [
    { id: "x1", name: "Xã Bù Đắp" },
    { id: "x2", name: "Xã Tân Hòa" },
    { id: "x3", name: "Xã Tân Lập" },
    { id: "x4", name: "Xã Tân Tài" },
    { id: "x5", name: "Xã Long Sơn" },
    { id: "x6", name: "Xã Tân Hạnh" },
    { id: "x7", name: "Xã Minh Thắng" },
    { id: "x8", name: "Xã Thạnh Hòa" },
    { id: "x9", name: "Xã Phú Thanh" },
    { id: "x10", name: "Xã Tân Tiến" },
    { id: "x11", name: "Xã Song Hòa" },
  ],
  // Huyện Chơn Thành
  ct_bp: [
    { id: "x1", name: "Xã Chơn Thành" },
    { id: "x2", name: "Xã Tân Lợi" },
    { id: "x3", name: "Xã An Lộc" },
    { id: "x4", name: "Xã Hoà Tân" },
    { id: "x5", name: "Xã Bình Thắng" },
    { id: "x6", name: "Xã Hòa Bình" },
    { id: "x7", name: "Xã Tân Phong" },
    { id: "x8", name: "Xã Tân Thành" },
    { id: "x9", name: "Xã Minh Hòa" },
  ],
  // Huyện Lộc Ninh
  ln: [
    { id: "x1", name: "Xã Lộc Ninh" },
    { id: "x2", name: "Xã Tân Lập" },
    { id: "x3", name: "Xã Phú Lộc" },
    { id: "x4", name: "Xã Bình Sơn" },
    { id: "x5", name: "Xã Tân Hạnh" },
    { id: "x6", name: "Xã Minh Phước" },
    { id: "x7", name: "Xã Quốc Tuấn" },
    { id: "x8", name: "Xã Tân Lân" },
  ],

  // ======================== BÌNH ĐỊNH (TP Quy Nhơn) ========================
  qn: [
    { id: "p1", name: "Phường Quy Nhơn" },
    { id: "p2", name: "Phường Trần Hưng Đạo" },
    { id: "p3", name: "Phường Nguyễn Hữu Cảnh" },
    { id: "p4", name: "Phường Bình Dương" },
    { id: "p5", name: "Phường Bình Hải" },
    { id: "p6", name: "Phường Ngô Mây" },
    { id: "p7", name: "Phường Lê Lợi" },
    { id: "p8", name: "Phường Hoàng Văn Thụ" },
    { id: "p9", name: "Phường Hồng Hòa" },
    { id: "p10", name: "Phường Thọ Quang" },
    { id: "p11", name: "Phường Nhân Hòa" },
    { id: "p12", name: "Phường Quang Trung" },
  ],
  // Huyện Phù Cát
  pc: [
    { id: "x1", name: "Xã Phù Cát" },
    { id: "x2", name: "Xã Tây An" },
    { id: "x3", name: "Xã Tây Sơn" },
    { id: "x4", name: "Xã Hòa Thắng" },
    { id: "x5", name: "Xã Tân Hòa" },
    { id: "x6", name: "Xã Quảng Phương" },
    { id: "x7", name: "Xã Tân Tây" },
    { id: "x8", name: "Xã Đại Sơn" },
    { id: "x9", name: "Xã Hòa Sơn" },
    { id: "x10", name: "Xã Minh Tân" },
  ],
  // Huyện Tây Sơn
  ts_bd: [
    { id: "x1", name: "Xã Tây Sơn" },
    { id: "x2", name: "Xã Tây An" },
    { id: "x3", name: "Xã Tây Hòa" },
    { id: "x4", name: "Xã Hòa Thắng" },
    { id: "x5", name: "Xã Hòa An" },
    { id: "x6", name: "Xã Tây Mỹ" },
    { id: "x7", name: "Xã Tây Bảo" },
    { id: "x8", name: "Xã Quảng Tân" },
    { id: "x9", name: "Xã Minh Tân" },
  ],

  // ======================== BÌNH THUẬN (TP Phan Thiết) ========================
  pt_bt: [
    { id: "p1", name: "Phường Phan Thiết" },
    { id: "p2", name: "Phường Phú Hài" },
    { id: "p3", name: "Phường Mỹ Xuân" },
    { id: "p4", name: "Phường Thanh Hải" },
    { id: "p5", name: "Phường Bình Hòa" },
    { id: "p6", name: "Phường Hàm Tiến" },
    { id: "p7", name: "Phường Hàm Rồng" },
    { id: "p8", name: "Phường Hồng Sơn" },
    { id: "p9", name: "Phường Cát Lái" },
    { id: "p10", name: "Phường Bích Họa" },
    { id: "p11", name: "Phường Thiên Hương" },
    { id: "p12", name: "Phường Hàm Minh" },
  ],
  // Huyện Tuy Phong
  tp_bt: [
    { id: "x1", name: "Xã Tuy Phong" },
    { id: "x2", name: "Xã Tân Lộc" },
    { id: "x3", name: "Xã Hàm Ninh" },
    { id: "x4", name: "Xã Xuyên Mộc" },
    { id: "x5", name: "Xã Phú Hội" },
    { id: "x6", name: "Xã Quốc Hòa" },
    { id: "x7", name: "Xã Tây Hòa" },
    { id: "x8", name: "Xã Tây Sơn" },
    { id: "x9", name: "Xã Tân Hòa" },
  ],
  // Huyện Hàm Thuận Nam
  htn: [
    { id: "x1", name: "Xã Hàm Thuận Nam" },
    { id: "x2", name: "Xã Hàm Hợp" },
    { id: "x3", name: "Xã Tà Chìa" },
    { id: "x4", name: "Xã Kế Sặc" },
    { id: "x5", name: "Xã Hàm Tiến" },
    { id: "x6", name: "Xã Tân Lộc" },
    { id: "x7", name: "Xã Minh Châu" },
    { id: "x8", name: "Xã Hồng Hạnh" },
  ],
  // Huyện Hàm Thuận Bắc
  htb_bt: [
    { id: "x1", name: "Xã Hàm Thuận Bắc" },
    { id: "x2", name: "Xã Bình Hà" },
    { id: "x3", name: "Xã Tân Phú" },
    { id: "x4", name: "Xã Tân Tài" },
    { id: "x5", name: "Xã Khe Xanh" },
    { id: "x6", name: "Xã Vượng Tân" },
    { id: "x7", name: "Xã Bình Gia" },
  ],

  // ======================== BÌNH DƯƠNG (TP Thủ Dầu Một) ========================
  tdm: [
    { id: "p1", name: "Phường Thủ Dầu Một" },
    { id: "p2", name: "Phường Tân Định" },
    { id: "p3", name: "Phường Tân Phong" },
    { id: "p4", name: "Phường Thống Nhất" },
    { id: "p5", name: "Phường Tân Hòa" },
    { id: "p6", name: "Phường Phú Lợi" },
    { id: "p7", name: "Phường Hiệp Thành" },
    { id: "p8", name: "Phường Lái Thiêu" },
    { id: "p9", name: "Phường Hòa Lạc" },
    { id: "p10", name: "Phường Bình Chuẩn" },
    { id: "p11", name: "Phường Hiệp Bình" },
    { id: "p12", name: "Phường An Ninh" },
  ],
  // Huyện Bến Cát
  bc_bd: [
    { id: "x1", name: "Xã Bến Cát" },
    { id: "x2", name: "Xã Tân Tạo" },
    { id: "x3", name: "Xã Tân Hiệp" },
    { id: "x4", name: "Xã Tây Thạnh" },
    { id: "x5", name: "Xã Thanh Tây" },
    { id: "x6", name: "Xã Song Tấn" },
    { id: "x7", name: "Xã Tân Khanh" },
    { id: "x8", name: "Xã Tân Lợi" },
    { id: "x9", name: "Xã Tân Phúc" },
    { id: "x10", name: "Xã Bình Chuẩn" },
  ],
  // Huyện Bàu Bàng
  bb_bd: [
    { id: "x1", name: "Xã Bàu Bàng" },
    { id: "x2", name: "Xã Tân Lợi" },
    { id: "x3", name: "Xã Thanh Tây" },
    { id: "x4", name: "Xã Tân Thắng" },
    { id: "x5", name: "Xã Song Tấn" },
    { id: "x6", name: "Xã Tây Hạnh" },
    { id: "x7", name: "Xã Tân Tạo" },
    { id: "x8", name: "Xã Hòa Lạc" },
  ],
  // Huyện Phú Giáo
  pg: [
    { id: "x1", name: "Xã Phú Giáo" },
    { id: "x2", name: "Xã Tân Thắng" },
    { id: "x3", name: "Xã Tân Lợi" },
    { id: "x4", name: "Xã Thanh Tây" },
    { id: "x5", name: "Xã Tây Hạnh" },
    { id: "x6", name: "Xã Tây Tạo" },
    { id: "x7", name: "Xã Bình Chuẩn" },
  ],

  // ======================== CÀ MAU (TP Cà Mau) ========================
  cm: [
    { id: "p1", name: "Phường 1" },
    { id: "p2", name: "Phường 2" },
    { id: "p3", name: "Phường 3" },
    { id: "p4", name: "Phường 4" },
    { id: "p5", name: "Phường 5" },
    { id: "p6", name: "Phường 6" },
    { id: "p7", name: "Phường Nông Trang" },
    { id: "p8", name: "Phường Cái Dăm" },
    { id: "p9", name: "Phường Tân An" },
    { id: "p10", name: "Phường Vĩnh Hòa" },
    { id: "p11", name: "Phường Mỹ Xuyên" },
    { id: "p12", name: "Phường Duyên Hải" },
  ],
  // Huyện Cà Mau
  cm_hc: [
    { id: "x1", name: "Xã Cà Mau" },
    { id: "x2", name: "Xã Tân Thạnh" },
    { id: "x3", name: "Xã Tân Lập" },
    { id: "x4", name: "Xã Hồng Dân" },
    { id: "x5", name: "Xã Khánh Hòa" },
    { id: "x6", name: "Xã Thanh Thắng" },
    { id: "x7", name: "Xã Tân Uyên" },
    { id: "x8", name: "Xã Phước Long" },
    { id: "x9", name: "Xã Mỹ Khánh" },
  ],
  // Huyện Năm Căn
  nc_cm: [
    { id: "x1", name: "Xã Năm Căn" },
    { id: "x2", name: "Xã Tân Thạnh" },
    { id: "x3", name: "Xã An Khánh" },
    { id: "x4", name: "Xã Cái Côn" },
    { id: "x5", name: "Xã Tân Tiến" },
    { id: "x6", name: "Xã Khánh Hòa" },
    { id: "x7", name: "Xã Tân Hiệp" },
  ],
  // Huyện U Minh
  um: [
    { id: "x1", name: "Xã U Minh" },
    { id: "x2", name: "Xã Tân Khánh" },
    { id: "x3", name: "Xã Tân Tạo" },
    { id: "x4", name: "Xã Mỹ Tây" },
    { id: "x5", name: "Xã Khánh Thắng" },
    { id: "x6", name: "Xã Tân Phong" },
  ],

  // ======================== CAO BẰNG (TP Cao Bằng) ========================
  cb: [
    { id: "p1", name: "Phường Cao Bằng" },
    { id: "p2", name: "Phường Phục Hoà" },
    { id: "p3", name: "Phường Quảng Hòa" },
    { id: "p4", name: "Phường Phan Kiển" },
    { id: "p5", name: "Phường Thái Sơn" },
    { id: "p6", name: "Phường Quy Sơn" },
    { id: "p7", name: "Phường Hồng Hà" },
    { id: "p8", name: "Phường Hạ Long" },
    { id: "p9", name: "Phường Nước Mặn" },
    { id: "p10", name: "Phường Lâm Hòa" },
    { id: "p11", name: "Phường Bạch Đằng" },
  ],
  // Huyện Bảo Lâm
  bl_cb: [
    { id: "x1", name: "Xã Bảo Lâm" },
    { id: "x2", name: "Xã Tân Thắng" },
    { id: "x3", name: "Xã Tân Lập" },
    { id: "x4", name: "Xã Quảng Phú" },
    { id: "x5", name: "Xã Hòa Thắng" },
    { id: "x6", name: "Xã Yên Hòa" },
    { id: "x7", name: "Xã Tây Sơn" },
    { id: "x8", name: "Xã Minh Hòa" },
  ],
  // Huyện Thái Nguyên
  tng_cb: [
    { id: "x1", name: "Xã Thái Nguyên" },
    { id: "x2", name: "Xã Thanh Thắng" },
    { id: "x3", name: "Xã Thanh Lạng" },
    { id: "x4", name: "Xã Tân Phong" },
    { id: "x5", name: "Xã Tân Sơn" },
    { id: "x6", name: "Xã Quảng Hoà" },
    { id: "x7", name: "Xã Hồng Hạ" },
  ],
  // Huyện Hạ Lang
  hl_cb: [
    { id: "x1", name: "Xã Hạ Lang" },
    { id: "x2", name: "Xã Yên Sơn" },
    { id: "x3", name: "Xã Minh Tân" },
    { id: "x4", name: "Xã Hoà Thắng" },
    { id: "x5", name: "Xã Tân Lập" },
    { id: "x6", name: "Xã Tây Hòa" },
  ],

  // ======================== ĐIỆN BIÊN (TP Điện Biên Phủ) ========================
  db: [
    { id: "p1", name: "Phường Điện Biên Phủ" },
    { id: "p2", name: "Phường Quang Trung" },
    { id: "p3", name: "Phường Tây Sơn" },
    { id: "p4", name: "Phường Tráng Xà" },
    { id: "p5", name: "Phường Bội Sơn" },
    { id: "p6", name: "Phường Tuyên Quang" },
    { id: "p7", name: "Phường Thanh Nê" },
    { id: "p8", name: "Phường Thụ Sơn" },
    { id: "p9", name: "Phường Nông Sơn" },
  ],
  // Huyện Mường Ảng
  ma: [
    { id: "x1", name: "Xã Mường Ảng" },
    { id: "x2", name: "Xã Tây Sơn" },
    { id: "x3", name: "Xã Thanh Thắng" },
    { id: "x4", name: "Xã Yên Sơn" },
    { id: "x5", name: "Xã Hòa Bình" },
    { id: "x6", name: "Xã Tây Hòa" },
    { id: "x7", name: "Xã Quảng Phú" },
  ],
  // Huyện Mường Chà
  mch: [
    { id: "x1", name: "Xã Mường Chà" },
    { id: "x2", name: "Xã Tân Sơn" },
    { id: "x3", name: "Xã Phong Sơn" },
    { id: "x4", name: "Xã Tây Tạo" },
    { id: "x5", name: "Xã Quảng Phú" },
    { id: "x6", name: "Xã Tân Hòa" },
  ],
  // Huyện Tủa Chùa
  tch: [
    { id: "x1", name: "Xã Tủa Chùa" },
    { id: "x2", name: "Xã Tân Lập" },
    { id: "x3", name: "Xã Phong Hòa" },
    { id: "x4", name: "Xã Quảng Sơn" },
    { id: "x5", name: "Xã Hòa Sơn" },
  ],

  // ======================== ĐẮK LẮK (TP Buôn Ma Thuột) ========================
  dl: [
    { id: "p1", name: "Phường Buôn Ma Thuột" },
    { id: "p2", name: "Phường An Phú" },
    { id: "p3", name: "Phường Tân Thành" },
    { id: "p4", name: "Phường Thống Nhất" },
    { id: "p5", name: "Phường Tây Sơn" },
    { id: "p6", name: "Phường Tây An" },
    { id: "p7", name: "Phường Hòa Lạc" },
    { id: "p8", name: "Phường Quang Trung" },
    { id: "p9", name: "Phường Hòa Phong" },
    { id: "p10", name: "Phường Hằng Bông" },
    { id: "p11", name: "Phường Xuân Hòa" },
  ],
  // Huyện Krông Năng
  kn: [
    { id: "x1", name: "Xã Krông Năng" },
    { id: "x2", name: "Xã Tân Thắng" },
    { id: "x3", name: "Xã Tân Lập" },
    { id: "x4", name: "Xã Hòa Bình" },
    { id: "x5", name: "Xã Tân Hòa" },
    { id: "x6", name: "Xã Hiệp Hòa" },
    { id: "x7", name: "Xã Yên Sơn" },
    { id: "x8", name: "Xã Tây Sơn" },
  ],
  // Huyện Krông Bông
  kb: [
    { id: "x1", name: "Xã Krông Bông" },
    { id: "x2", name: "Xã Tây Sơn" },
    { id: "x3", name: "Xã Tân Thanh" },
    { id: "x4", name: "Xã Yên An" },
    { id: "x5", name: "Xã Hòa Sơn" },
    { id: "x6", name: "Xã Tân Lập" },
    { id: "x7", name: "Xã Quảng Phú" },
  ],
  // Huyện Lắk
  lak: [
    { id: "x1", name: "Xã Lắk" },
    { id: "x2", name: "Xã Tân Hòa" },
    { id: "x3", name: "Xã Hiệp Hòa" },
    { id: "x4", name: "Xã Tây Sơn" },
    { id: "x5", name: "Xã Thanh Tân" },
    { id: "x6", name: "Xã Yên Sơn" },
  ],

  // ======================== ĐỒNG THÁP (TP Cao Lãnh) ========================
  dt: [
    { id: "p1", name: "Phường Cao Lãnh" },
    { id: "p2", name: "Phường Châu Phú" },
    { id: "p3", name: "Phường Mỹ Phú" },
    { id: "p4", name: "Phường Tân Thạnh" },
    { id: "p5", name: "Phường Hòa Bình" },
    { id: "p6", name: "Phường Hòa Lạc" },
    { id: "p7", name: "Phường An Bình" },
    { id: "p8", name: "Phường Hợp Tài" },
    { id: "p9", name: "Phường Hương Sơn" },
    { id: "p10", name: "Phường Lý Thái Tông" },
    { id: "p11", name: "Phường Quang Trung" },
    { id: "p12", name: "Phường Thanh Sơn" },
  ],
  // Huyện Hồng Ngu
  hn_dt: [
    { id: "x1", name: "Xã Hồng Ngu" },
    { id: "x2", name: "Xã Tân Tạo" },
    { id: "x3", name: "Xã Tân Lập" },
    { id: "x4", name: "Xã Tây Sơn" },
    { id: "x5", name: "Xã Hòa Bình" },
    { id: "x6", name: "Xã Thanh Tây" },
    { id: "x7", name: "Xã Mỹ Hòa" },
    { id: "x8", name: "Xã Tân Hòa" },
  ],
  // Huyện Lấp Vò
  lv: [
    { id: "x1", name: "Xã Lấp Vò" },
    { id: "x2", name: "Xã Tân Thạnh" },
    { id: "x3", name: "Xã Tân Lập" },
    { id: "x4", name: "Xã Thanh Bình" },
    { id: "x5", name: "Xã Quảng Tân" },
    { id: "x6", name: "Xã Minh Hòa" },
  ],
  // Huyện Tháp Mười
  tm: [
    { id: "x1", name: "Xã Tháp Mười" },
    { id: "x2", name: "Xã Tân Thiện" },
    { id: "x3", name: "Xã Tân Tạo" },
    { id: "x4", name: "Xã Tây Sơn" },
    { id: "x5", name: "Xã Hiệp Hòa" },
    { id: "x6", name: "Xã Thanh Tây" },
  ],

  // ======================== ĐỒNG NAI (TP Biên Hòa) ========================
  dn: [
    { id: "p1", name: "Phường Biên Hòa" },
    { id: "p2", name: "Phường Thống Nhất" },
    { id: "p3", name: "Phường Quyết Thắng" },
    { id: "p4", name: "Phường Tân Phong" },
    { id: "p5", name: "Phường Tân Hạ" },
    { id: "p6", name: "Phường Hòa Bình" },
    { id: "p7", name: "Phường Hiệp Hòa" },
    { id: "p8", name: "Phường Bình Hòa" },
    { id: "p9", name: "Phường Tân Thanh" },
    { id: "p10", name: "Phường Bàu Cạn" },
    { id: "p11", name: "Phường Hồng Bàng" },
    { id: "p12", name: "Phường Hiệp Thành" },
  ],
  // Huyện Thống Nhất
  tn_dn: [
    { id: "x1", name: "Xã Thống Nhất" },
    { id: "x2", name: "Xã Tân Tạo" },
    { id: "x3", name: "Xã Tân Lập" },
    { id: "x4", name: "Xã Tây Sơn" },
    { id: "x5", name: "Xã Thanh Bình" },
    { id: "x6", name: "Xã Quảng Tân" },
    { id: "x7", name: "Xã Hiệp Hòa" },
  ],
  // Huyện Trảng Bom
  tb_dn: [
    { id: "x1", name: "Xã Trảng Bom" },
    { id: "x2", name: "Xã Tân Thạnh" },
    { id: "x3", name: "Xã Tân Lập" },
    { id: "x4", name: "Xã Tâm Hiệp" },
    { id: "x5", name: "Xã Tân Hòa" },
    { id: "x6", name: "Xã Thanh Tây" },
  ],
  // Huyện Long Thành
  lt_dn: [
    { id: "x1", name: "Xã Long Thành" },
    { id: "x2", name: "Xã Tân Hồng" },
    { id: "x3", name: "Xã Tân Thanh" },
    { id: "x4", name: "Xã Tây Sơn" },
    { id: "x5", name: "Xã Tân Lập" },
    { id: "x6", name: "Xã Hiệp Phương" },
  ],

  // ======================== GIA LAI (TP Pleiku) ========================
  gl: [
    { id: "p1", name: "Phường Pleiku" },
    { id: "p2", name: "Phường Yên Thế" },
    { id: "p3", name: "Phường Tây Sơn" },
    { id: "p4", name: "Phường Quảng Trị" },
    { id: "p5", name: "Phường Tây An" },
    { id: "p6", name: "Phường Thống Nhất" },
    { id: "p7", name: "Phường Tân Thành" },
    { id: "p8", name: "Phường Hòa Lạc" },
    { id: "p9", name: "Phường Dương Sơn" },
    { id: "p10", name: "Phường Lê Duẩn" },
    { id: "p11", name: "Phường Tây Giang" },
  ],
  // Huyện Chư Sê
  cs: [
    { id: "x1", name: "Xã Chư Sê" },
    { id: "x2", name: "Xã Tân Thắng" },
    { id: "x3", name: "Xã Tây Sơn" },
    { id: "x4", name: "Xã Quảng Phú" },
    { id: "x5", name: "Xã Hiệp Hòa" },
    { id: "x6", name: "Xã Thanh Sơn" },
    { id: "x7", name: "Xã Tân Lập" },
  ],
  // Huyện Chư Prông
  cp_gl: [
    { id: "x1", name: "Xã Chư Prông" },
    { id: "x2", name: "Xã Tây Sơn" },
    { id: "x3", name: "Xã Tân Thanh" },
    { id: "x4", name: "Xã Yên An" },
    { id: "x5", name: "Xã Hòa Sơn" },
    { id: "x6", name: "Xã Tân Lập" },
  ],
  // Huyện Krông Pa
  kp: [
    { id: "x1", name: "Xã Krông Pa" },
    { id: "x2", name: "Xã Tân Hòa" },
    { id: "x3", name: "Xã Thanh Tân" },
    { id: "x4", name: "Xã Yên Sơn" },
    { id: "x5", name: "Xã Quảng Phú" },
  ],

  // ======================== HÀ GIANG (TP Hà Giang) ========================
  hg: [
    { id: "p1", name: "Phường Hà Giang" },
    { id: "p2", name: "Phường Trung Tâm" },
    { id: "p3", name: "Phường Tây Sơn" },
    { id: "p4", name: "Phường Quảng Hòa" },
    { id: "p5", name: "Phường Tân Tây" },
    { id: "p6", name: "Phường Phú Lương" },
    { id: "p7", name: "Phường Thị Trấn" },
    { id: "p8", name: "Phường Hằng Gòn" },
    { id: "p9", name: "Phường Bình Chân" },
  ],
  // Huyện Đông Văn
  dv_hg: [
    { id: "x1", name: "Xã Đông Văn" },
    { id: "x2", name: "Xã Tân Lập" },
    { id: "x3", name: "Xã Yên Thế" },
    { id: "x4", name: "Xã Tân Thanh" },
    { id: "x5", name: "Xã Quảng Phú" },
    { id: "x6", name: "Xã Hòa An" },
  ],
  // Huyện Mèo Vạc
  mv: [
    { id: "x1", name: "Xã Mèo Vạc" },
    { id: "x2", name: "Xã Tây Sơn" },
    { id: "x3", name: "Xã Thanh Tân" },
    { id: "x4", name: "Xã Tân Hòa" },
    { id: "x5", name: "Xã Hiệp Hòa" },
  ],
  // Huyện Yên Minh
  ym: [
    { id: "x1", name: "Xã Yên Minh" },
    { id: "x2", name: "Xã Tân Lập" },
    { id: "x3", name: "Xã Tây An" },
    { id: "x4", name: "Xã Quảng Phú" },
    { id: "x5", name: "Xã Tân Hòa" },
  ],

  // ======================== HÀ TĨNH (TP Hà Tĩnh) ========================
  ht: [
    { id: "p1", name: "Phường Hà Tĩnh" },
    { id: "p2", name: "Phường Trung Tâm" },
    { id: "p3", name: "Phường Tây Sơn" },
    { id: "p4", name: "Phường Quảng Hòa" },
    { id: "p5", name: "Phường Tân Tây" },
    { id: "p6", name: "Phường Phú Lương" },
    { id: "p7", name: "Phường Thị Trấn" },
    { id: "p8", name: "Phường Hằng Gòn" },
    { id: "p9", name: "Phường Bình Chân" },
    { id: "p10", name: "Phường Hạnh Lợi" },
  ],
  // Huyện Hương Khê
  hk_ht: [
    { id: "x1", name: "Xã Hương Khê" },
    { id: "x2", name: "Xã Tân Lập" },
    { id: "x3", name: "Xã Yên Thế" },
    { id: "x4", name: "Xã Tân Thanh" },
    { id: "x5", name: "Xã Quảng Phú" },
    { id: "x6", name: "Xã Hòa An" },
    { id: "x7", name: "Xã Thanh Sơn" },
  ],
  // Huyện Kỳ Anh
  ka_ht: [
    { id: "x1", name: "Xã Kỳ Anh" },
    { id: "x2", name: "Xã Tây Sơn" },
    { id: "x3", name: "Xã Thanh Tân" },
    { id: "x4", name: "Xã Tân Hòa" },
    { id: "x5", name: "Xã Hiệp Hòa" },
    { id: "x6", name: "Xã Yên Sơn" },
  ],
  // Huyện Thạch Hà
  th_ht: [
    { id: "x1", name: "Xã Thạch Hà" },
    { id: "x2", name: "Xã Tân Thanh" },
    { id: "x3", name: "Xã Tây An" },
    { id: "x4", name: "Xã Quảng Sơn" },
    { id: "x5", name: "Xã Tân Lập" },
  ],

  // ======================== HÀI DƯƠNG (TP Hải Dương) ========================
  hd: [
    { id: "p1", name: "Phường Hải Dương" },
    { id: "p2", name: "Phường Cầu Ninh" },
    { id: "p3", name: "Phường Thành Công" },
    { id: "p4", name: "Phường Tây Sơn" },
    { id: "p5", name: "Phường Quảng Hòa" },
    { id: "p6", name: "Phường Tân Tây" },
    { id: "p7", name: "Phường Minh Phú" },
    { id: "p8", name: "Phường Bắc Sơn" },
    { id: "p9", name: "Phường Hòa Bình" },
    { id: "p10", name: "Phường Trần Phú" },
  ],
  // Huyện Chí Linh
  cl_hd: [
    { id: "x1", name: "Xã Chí Linh" },
    { id: "x2", name: "Xã Tân Tạo" },
    { id: "x3", name: "Xã Tân Lập" },
    { id: "x4", name: "Xã Tây Sơn" },
    { id: "x5", name: "Xã Thanh Bình" },
    { id: "x6", name: "Xã Quảng Tân" },
    { id: "x7", name: "Xã Hiệp Hòa" },
  ],
  // Huyện Kiến Xương
  kx: [
    { id: "x1", name: "Xã Kiến Xương" },
    { id: "x2", name: "Xã Tân Thanh" },
    { id: "x3", name: "Xã Tân Tạo" },
    { id: "x4", name: "Xã Yên An" },
    { id: "x5", name: "Xã Hòa Sơn" },
  ],
  // Huyện Thanh Hà
  th_hd: [
    { id: "x1", name: "Xã Thanh Hà" },
    { id: "x2", name: "Xã Tân Lập" },
    { id: "x3", name: "Xã Tây An" },
    { id: "x4", name: "Xã Quảng Sơn" },
    { id: "x5", name: "Xã Tân Hòa" },
  ],

  // ======================== HẬU GIANG (TP Vị Thanh) ========================
  hg2: [
    { id: "p1", name: "Phường Vị Thanh" },
    { id: "p2", name: "Phường 1" },
    { id: "p3", name: "Phường 2" },
    { id: "p4", name: "Phường 3" },
    { id: "p5", name: "Phường 4" },
    { id: "p6", name: "Phường 5" },
    { id: "p7", name: "Phường 6" },
    { id: "p8", name: "Phường Nhân Hòa" },
    { id: "p9", name: "Phường Tân An" },
    { id: "p10", name: "Phường Cái Dăm" },
  ],
  // Huyện Hậu Giang
  hg2_hc: [
    { id: "x1", name: "Xã Hậu Giang" },
    { id: "x2", name: "Xã Tân Tạo" },
    { id: "x3", name: "Xã Tân Lập" },
    { id: "x4", name: "Xã Thanh Bình" },
    { id: "x5", name: "Xã Quảng Tân" },
    { id: "x6", name: "Xã Hiệp Hòa" },
  ],
  // Huyện Phụng Hiệp
  ph: [
    { id: "x1", name: "Xã Phụng Hiệp" },
    { id: "x2", name: "Xã Tây Sơn" },
    { id: "x3", name: "Xã Thanh Tân" },
    { id: "x4", name: "Xã Tân Hòa" },
    { id: "x5", name: "Xã Hiệp Hòa" },
  ],

  // ======================== HÒA BÌNH (TP Hòa Bình) ========================
  hb: [
    { id: "p1", name: "Phường Hòa Bình" },
    { id: "p2", name: "Phường Tây Sơn" },
    { id: "p3", name: "Phường Quảng Hòa" },
    { id: "p4", name: "Phường Tân Tây" },
    { id: "p5", name: "Phường Minh Phú" },
    { id: "p6", name: "Phường Bắc Sơn" },
    { id: "p7", name: "Phường Trần Hưng Đạo" },
    { id: "p8", name: "Phường Hàng Gòn" },
    { id: "p9", name: "Phường Hòa Xuân" },
  ],
  // Huyện Kim Bôi
  kb_hb: [
    { id: "x1", name: "Xã Kim Bôi" },
    { id: "x2", name: "Xã Tân Tạo" },
    { id: "x3", name: "Xã Tân Lập" },
    { id: "x4", name: "Xã Tây Sơn" },
    { id: "x5", name: "Xã Thanh Bình" },
    { id: "x6", name: "Xã Quảng Tân" },
  ],
  // Huyện Lạc Sơn
  ls_hb: [
    { id: "x1", name: "Xã Lạc Sơn" },
    { id: "x2", name: "Xã Tây Sơn" },
    { id: "x3", name: "Xã Thanh Tân" },
    { id: "x4", name: "Xã Tân Hòa" },
    { id: "x5", name: "Xã Hiệp Hòa" },
  ],
  // Huyện Tân Lạc
  tl_hb: [
    { id: "x1", name: "Xã Tân Lạc" },
    { id: "x2", name: "Xã Tân Thanh" },
    { id: "x3", name: "Xã Tây An" },
    { id: "x4", name: "Xã Quảng Sơn" },
    { id: "x5", name: "Xã Tân Lập" },
  ],

  // ======================== KHÁNH HÒA (TP Nha Trang) ========================
  kh: [
    { id: "p1", name: "Phường Nha Trang" },
    { id: "p2", name: "Phường Xương Huân" },
    { id: "p3", name: "Phường Vạn Thắng" },
    { id: "p4", name: "Phường Vạn Hải" },
    { id: "p5", name: "Phường Tây Sơn" },
    { id: "p6", name: "Phường Quảng Hòa" },
    { id: "p7", name: "Phường Tân Lợi" },
    { id: "p8", name: "Phường Bắc Sơn" },
    { id: "p9", name: "Phường Lộc Thánh" },
    { id: "p10", name: "Phường Phước Tân" },
    { id: "p11", name: "Phường Hòa Bình" },
    { id: "p12", name: "Phường Cửa Ông" },
  ],
  // Huyện Cam Ranh
  cr: [
    { id: "x1", name: "Xã Cam Ranh" },
    { id: "x2", name: "Xã Tân Lập" },
    { id: "x3", name: "Xã Tây An" },
    { id: "x4", name: "Xã Quảng Phú" },
    { id: "x5", name: "Xã Hòa An" },
    { id: "x6", name: "Xã Thanh Sơn" },
  ],
  // Huyện Diên Khánh
  dk_kh: [
    { id: "x1", name: "Xã Diên Khánh" },
    { id: "x2", name: "Xã Tân Thanh" },
    { id: "x3", name: "Xã Tây Sơn" },
    { id: "x4", name: "Xã Hiệp Hòa" },
    { id: "x5", name: "Xã Tân Hòa" },
  ],
  // Huyện Vạn Ninh
  vn_kh: [
    { id: "x1", name: "Xã Vạn Ninh" },
    { id: "x2", name: "Xã Tân Lập" },
    { id: "x3", name: "Xã Tây Tạo" },
    { id: "x4", name: "Xã Quảng Sơn" },
  ],

  // ======================== KIÊN GIANG (TP Rạch Giá) ========================
  kg: [
    { id: "p1", name: "Phường Rạch Giá" },
    { id: "p2", name: "Phường Vĩnh Mỹ" },
    { id: "p3", name: "Phường Vĩnh Tế" },
    { id: "p4", name: "Phường Thái Hòa" },
    { id: "p5", name: "Phường Tây Sơn" },
    { id: "p6", name: "Phường Quảng Hòa" },
    { id: "p7", name: "Phường Phương Tây" },
    { id: "p8", name: "Phường Hạnh Lợi" },
    { id: "p9", name: "Phường Phú Tân" },
    { id: "p10", name: "Phường Hồng Bàng" },
    { id: "p11", name: "Phường Bạch Đằng" },
  ],
  // Huyện Hòn Đất
  hd_kg: [
    { id: "x1", name: "Xã Hòn Đất" },
    { id: "x2", name: "Xã Tân Thanh" },
    { id: "x3", name: "Xã Tây An" },
    { id: "x4", name: "Xã Quảng Sơn" },
    { id: "x5", name: "Xã Tân Lập" },
    { id: "x6", name: "Xã Thanh Tây" },
  ],
  // Huyện Tân Hiệp
  th_kg: [
    { id: "x1", name: "Xã Tân Hiệp" },
    { id: "x2", name: "Xã Tân Tạo" },
    { id: "x3", name: "Xã Tây Sơn" },
    { id: "x4", name: "Xã Hòa Bình" },
    { id: "x5", name: "Xã Hiệp Hòa" },
  ],
  // Huyện Kiên Lương
  kl: [
    { id: "x1", name: "Xã Kiên Lương" },
    { id: "x2", name: "Xã Tân Thanh" },
    { id: "x3", name: "Xã Tây An" },
    { id: "x4", name: "Xã Quảng Phú" },
    { id: "x5", name: "Xã Hòa An" },
  ],

  // ======================== KON TUM (TP Kon Tum) ========================
  kt: [
    { id: "p1", name: "Phường Kon Tum" },
    { id: "p2", name: "Phường Thái Phiên" },
    { id: "p3", name: "Phường Tây Sơn" },
    { id: "p4", name: "Phường Tân Phú" },
    { id: "p5", name: "Phường Minh Khai" },
    { id: "p6", name: "Phường Bình Minh" },
    { id: "p7", name: "Phường Dương Quang" },
    { id: "p8", name: "Phường Hải Sơn" },
  ],
  // Huyện Kon Plong
  kpl: [
    { id: "x1", name: "Xã Kon Plong" },
    { id: "x2", name: "Xã Tây Sơn" },
    { id: "x3", name: "Xã Thanh Tân" },
    { id: "x4", name: "Xã Tân Hòa" },
    { id: "x5", name: "Xã Hiệp Hòa" },
  ],
  // Huyện Đắk Glei
  dg: [
    { id: "x1", name: "Xã Đắk Glei" },
    { id: "x2", name: "Xã Tân Thanh" },
    { id: "x3", name: "Xã Tây An" },
    { id: "x4", name: "Xã Quảng Phú" },
  ],

  // ======================== LAI CHÂU (TP Lai Châu) ========================
  lc: [
    { id: "p1", name: "Phường Lai Châu" },
    { id: "p2", name: "Phường Tàu" },
    { id: "p3", name: "Phường Tây Sơn" },
    { id: "p4", name: "Phường Tân Phú" },
    { id: "p5", name: "Phường Minh Khai" },
    { id: "p6", name: "Phường Bình Minh" },
    { id: "p7", name: "Phường Dương Quang" },
    { id: "p8", name: "Phường Hải Sơn" },
  ],

  // ======================== LÂM ĐỒNG ========================
  dl: [
    { id: "p1", name: "Phường Đà Lạt" },
    { id: "p2", name: "Phường Cam Ly" },
    { id: "p3", name: "Phường Tây Sơn" },
    { id: "p4", name: "Phường Hồng Hòa" },
    { id: "p5", name: "Phường Hòa Bình" },
    { id: "p6", name: "Phường Thanh Bình" },
    { id: "p7", name: "Phường Trung Tâm" },
    { id: "p8", name: "Phường Thượng Thị" },
    { id: "p9", name: "Phường Hòa Phong" },
    { id: "p10", name: "Phường Tây An" },
    { id: "p11", name: "Phường Thục Sơn" },
  ],
  dd_ld: [
    { id: "x1", name: "Xã Đất Đỏ" },
    { id: "x2", name: "Xã Tân Hà" },
    { id: "x3", name: "Xã Lâm Hòa" },
    { id: "x4", name: "Xã Thanh Bình" },
    { id: "x5", name: "Xã Thái Sơn" },
    { id: "x6", name: "Xã Hiền Lộc" },
  ],
  lh_ld: [
    { id: "x1", name: "Xã Lâm Hà" },
    { id: "x2", name: "Xã Tân Sơn" },
    { id: "x3", name: "Xã Lâm Thượng" },
    { id: "x4", name: "Xã Thái Lâm" },
    { id: "x5", name: "Xã Thanh Bình" },
  ],

  // ======================== LẠNG SƠN ========================
  ls: [
    { id: "p1", name: "Phường Lạng Sơn" },
    { id: "p2", name: "Phường Quảng Hòa" },
    { id: "p3", name: "Phường Tây Sơn" },
    { id: "p4", name: "Phường Tân Phú" },
    { id: "p5", name: "Phường Minh Khai" },
    { id: "p6", name: "Phường Bình Minh" },
    { id: "p7", name: "Phường Dương Quang" },
    { id: "p8", name: "Phường Hải Sơn" },
    { id: "p9", name: "Phường Thanh Bình" },
  ],
  chil: [
    { id: "x1", name: "Xã Chi Lăng" },
    { id: "x2", name: "Xã Tân Thanh" },
    { id: "x3", name: "Xã Lâm Hòa" },
    { id: "x4", name: "Xã Hiền Lộc" },
  ],
  nq_ls: [
    { id: "x1", name: "Xã Nà Qua" },
    { id: "x2", name: "Xã Tân Thanh" },
    { id: "x3", name: "Xã Lâm Hòa" },
  ],

  // ======================== LÀO CAI ========================
  lc2: [
    { id: "p1", name: "Phường Lào Cai" },
    { id: "p2", name: "Phường Bắc Cường" },
    { id: "p3", name: "Phường Vĩnh Tế" },
    { id: "p4", name: "Phường Tây Sơn" },
    { id: "p5", name: "Phường Quảng Hòa" },
    { id: "p6", name: "Phường Tân Tây" },
    { id: "p7", name: "Phường Phú Lương" },
    { id: "p8", name: "Phường Hàng Gòn" },
    { id: "p9", name: "Phường Hòa Bình" },
    { id: "p10", name: "Phường Trần Phú" },
    { id: "p11", name: "Phường Bạch Đằng" },
  ],
  bh_lc: [
    { id: "x1", name: "Xã Bạc Hà" },
    { id: "x2", name: "Xã Tân Thanh" },
    { id: "x3", name: "Xã Tây An" },
    { id: "x4", name: "Xã Quảng Sơn" },
  ],
  bt_lc: [
    { id: "x1", name: "Xã Bảo Thắng" },
    { id: "x2", name: "Xã Tân Lập" },
    { id: "x3", name: "Xã Tây Tạo" },
    { id: "x4", name: "Xã Quảng Phú" },
  ],

  // ======================== LONG AN ========================
  la: [
    { id: "p1", name: "Phường Tân An" },
    { id: "p2", name: "Phường 1" },
    { id: "p3", name: "Phường 2" },
    { id: "p4", name: "Phường 3" },
    { id: "p5", name: "Phường 4" },
    { id: "p6", name: "Phường 5" },
    { id: "p7", name: "Phường 6" },
    { id: "p8", name: "Phường 7" },
    { id: "p9", name: "Phường 8" },
    { id: "p10", name: "Phường 9" },
    { id: "p11", name: "Phường 10" },
  ],
  cg_la: [
    { id: "x1", name: "Xã Cần Giuộc" },
    { id: "x2", name: "Xã Tân Tạo" },
    { id: "x3", name: "Xã Tân Lập" },
    { id: "x4", name: "Xã Tây Sơn" },
    { id: "x5", name: "Xã Thanh Bình" },
  ],
  cd_la: [
    { id: "x1", name: "Xã Cần Đước" },
    { id: "x2", name: "Xã Tân Thanh" },
    { id: "x3", name: "Xã Tây An" },
    { id: "x4", name: "Xã Quảng Phú" },
  ],

  // ======================== NAM ĐỊNH ========================
  nd: [
    { id: "p1", name: "Phường Nam Định" },
    { id: "p2", name: "Phường Hải An" },
    { id: "p3", name: "Phường Bà Triệu" },
    { id: "p4", name: "Phường Hạ Long" },
    { id: "p5", name: "Phường Trung Tâm" },
    { id: "p6", name: "Phường Tây Sơn" },
    { id: "p7", name: "Phường Hòa Bình" },
    { id: "p8", name: "Phường An Bình" },
    { id: "p9", name: "Phường Nước Mặn" },
    { id: "p10", name: "Phường Thanh Sơn" },
  ],
  yy: [
    { id: "x1", name: "Xã Ý Yên" },
    { id: "x2", name: "Xã Tân Tạo" },
    { id: "x3", name: "Xã Tân Lập" },
    { id: "x4", name: "Xã Tây Sơn" },
    { id: "x5", name: "Xã Thanh Bình" },
  ],
  gt: [
    { id: "x1", name: "Xã Giao Thủy" },
    { id: "x2", name: "Xã Tân Thanh" },
    { id: "x3", name: "Xã Tây An" },
    { id: "x4", name: "Xã Quảng Phú" },
  ],

  // ======================== NGHỆ AN ========================
  na: [
    { id: "p1", name: "Phường Vinh" },
    { id: "p2", name: "Phường Bến Thủy" },
    { id: "p3", name: "Phường Trường Thi" },
    { id: "p4", name: "Phường Tân Phong" },
    { id: "p5", name: "Phường Hòa Bình" },
    { id: "p6", name: "Phường Hòa Lạc" },
    { id: "p7", name: "Phường Tây Sơn" },
    { id: "p8", name: "Phường Hòa Phong" },
    { id: "p9", name: "Phường Tây An" },
    { id: "p10", name: "Phường Hồng Hòa" },
    { id: "p11", name: "Phường Trung Tâm" },
  ],
  hn_na: [
    { id: "x1", name: "Xã Hưng Nguyên" },
    { id: "x2", name: "Xã Tân Tạo" },
    { id: "x3", name: "Xã Tân Lập" },
    { id: "x4", name: "Xã Thanh Bình" },
    { id: "x5", name: "Xã Quảng Tân" },
  ],
  as: [
    { id: "x1", name: "Xã Anh Sơn" },
    { id: "x2", name: "Xã Tân Thanh" },
    { id: "x3", name: "Xã Tây An" },
    { id: "x4", name: "Xã Quảng Phú" },
  ],

  // ======================== NINH THUẬN ========================
  nt: [
    { id: "p1", name: "Phường Ninh Thuận" },
    { id: "p2", name: "Phường Hàm Rồng" },
    { id: "p3", name: "Phường Hàm Kiêm" },
    { id: "p4", name: "Phường Tây Sơn" },
    { id: "p5", name: "Phường Tân Phú" },
    { id: "p6", name: "Phường Minh Khai" },
    { id: "p7", name: "Phường Bình Minh" },
    { id: "p8", name: "Phường Dương Quang" },
    { id: "p9", name: "Phường Hải Sơn" },
  ],
  nh: [
    { id: "x1", name: "Xã Ninh Hải" },
    { id: "x2", name: "Xã Tân Lập" },
    { id: "x3", name: "Xã Tây Tạo" },
    { id: "x4", name: "Xã Quảng Phú" },
  ],

  // ======================== NINH BÌNH ========================
  nb: [
    { id: "p1", name: "Phường Ninh Bình" },
    { id: "p2", name: "Phường Trần Hưng Đạo" },
    { id: "p3", name: "Phường Lộc Bạn" },
    { id: "p4", name: "Phường Tây Sơn" },
    { id: "p5", name: "Phường Tân Phú" },
    { id: "p6", name: "Phường Minh Khai" },
    { id: "p7", name: "Phường Bình Minh" },
    { id: "p8", name: "Phường Dương Quang" },
    { id: "p9", name: "Phường Hải Sơn" },
    { id: "p10", name: "Phường Thanh Bình" },
    { id: "p11", name: "Phường Trung Tâm" },
  ],
  gv_nb: [
    { id: "x1", name: "Xã Gia Viễn" },
    { id: "x2", name: "Xã Tân Thanh" },
    { id: "x3", name: "Xã Tây An" },
    { id: "x4", name: "Xã Quảng Sơn" },
    { id: "x5", name: "Xã Tân Lập" },
  ],

  // ======================== PHÚ THỌ ========================
  pt: [
    { id: "p1", name: "Phường Phú Thọ" },
    { id: "p2", name: "Phường Trần Phú" },
    { id: "p3", name: "Phường Phú Thị" },
    { id: "p4", name: "Phường Tây Sơn" },
    { id: "p5", name: "Phường Tân Phú" },
    { id: "p6", name: "Phường Minh Khai" },
    { id: "p7", name: "Phường Bình Minh" },
    { id: "p8", name: "Phường Dương Quang" },
    { id: "p9", name: "Phường Hải Sơn" },
    { id: "p10", name: "Phường Thanh Bình" },
    { id: "p11", name: "Phường Trung Tâm" },
  ],
  tb_pt: [
    { id: "x1", name: "Xã Thanh Ba" },
    { id: "x2", name: "Xã Tân Thanh" },
    { id: "x3", name: "Xã Tây An" },
    { id: "x4", name: "Xã Quảng Sơn" },
    { id: "x5", name: "Xã Tân Lập" },
  ],

  // ======================== PHÚ YÊN ========================
  py: [
    { id: "p1", name: "Phường Tuy Hòa" },
    { id: "p2", name: "Phường An Phú" },
    { id: "p3", name: "Phường Phú Thịnh" },
    { id: "p4", name: "Phường Tây Sơn" },
    { id: "p5", name: "Phường Tân Phú" },
    { id: "p6", name: "Phường Minh Khai" },
    { id: "p7", name: "Phường Bình Minh" },
    { id: "p8", name: "Phường Dương Quang" },
    { id: "p9", name: "Phường Hải Sơn" },
    { id: "p10", name: "Phường Thanh Bình" },
  ],
  ph_py: [
    { id: "x1", name: "Xã Phú Hòa" },
    { id: "x2", name: "Xã Tân Thanh" },
    { id: "x3", name: "Xã Tây An" },
    { id: "x4", name: "Xã Quảng Sơn" },
    { id: "x5", name: "Xã Tân Lập" },
  ],

  // ======================== QUẢNG BÌNH ========================
  qb: [
    { id: "p1", name: "Phường Đông Hà" },
    { id: "p2", name: "Phường Bắc Sơn" },
    { id: "p3", name: "Phường Hải Thượng" },
    { id: "p4", name: "Phường Tây Sơn" },
    { id: "p5", name: "Phường Tân Phú" },
    { id: "p6", name: "Phường Minh Khai" },
    { id: "p7", name: "Phường Bình Minh" },
    { id: "p8", name: "Phường Dương Quang" },
    { id: "p9", name: "Phường Hải Sơn" },
    { id: "p10", name: "Phường Thanh Bình" },
  ],
  qb_hc: [
    { id: "x1", name: "Xã Quảng Bình" },
    { id: "x2", name: "Xã Tân Thanh" },
    { id: "x3", name: "Xã Tây An" },
    { id: "x4", name: "Xã Quảng Sơn" },
  ],

  // ======================== QUẢNG NAM ========================
  qa: [
    { id: "p1", name: "Phường Hội An" },
    { id: "p2", name: "Phường Minh An" },
    { id: "p3", name: "Phường Cẩm An" },
    { id: "p4", name: "Phường Cẩm Phô" },
    { id: "p5", name: "Phường Hòa Nơi" },
    { id: "p6", name: "Phường Hòa Nhân" },
    { id: "p7", name: "Phường Hòa Bình" },
    { id: "p8", name: "Phường Hòa Lạc" },
    { id: "p9", name: "Phường Thanh Hà" },
    { id: "p10", name: "Phường Tây Sơn" },
    { id: "p11", name: "Phường Trung Tâm" },
  ],
  tb_qa: [
    { id: "x1", name: "Xã Thăng Bình" },
    { id: "x2", name: "Xã Tân Thanh" },
    { id: "x3", name: "Xã Tây An" },
    { id: "x4", name: "Xã Quảng Sơn" },
    { id: "x5", name: "Xã Tân Lập" },
  ],

  // ======================== QUẢNG NGÃI ========================
  qn: [
    { id: "p1", name: "Phường Quảng Ngãi" },
    { id: "p2", name: "Phường Trần Hưng Đạo" },
    { id: "p3", name: "Phường Tịnh Kỳ" },
    { id: "p4", name: "Phường Tây Sơn" },
    { id: "p5", name: "Phường Tân Phú" },
    { id: "p6", name: "Phường Minh Khai" },
    { id: "p7", name: "Phường Bình Minh" },
    { id: "p8", name: "Phường Dương Quang" },
    { id: "p9", name: "Phường Hải Sơn" },
    { id: "p10", name: "Phường Thanh Bình" },
  ],
  qn_hc: [
    { id: "x1", name: "Xã Quảng Ngãi" },
    { id: "x2", name: "Xã Tân Thanh" },
    { id: "x3", name: "Xã Tây An" },
    { id: "x4", name: "Xã Quảng Sơn" },
    { id: "x5", name: "Xã Tân Lập" },
  ],

  // ======================== QUẢNG NINH ========================
  qn2: [
    { id: "p1", name: "Phường Hạ Long" },
    { id: "p2", name: "Phường Hồng Gai" },
    { id: "p3", name: "Phường Bãi Cháy" },
    { id: "p4", name: "Phường Tân Phong" },
    { id: "p5", name: "Phường Quảng Hòa" },
    { id: "p6", name: "Phường Tây Sơn" },
    { id: "p7", name: "Phường Hòa Lạc" },
    { id: "p8", name: "Phường Hòa Bình" },
    { id: "p9", name: "Phường Thanh Lợi" },
    { id: "p10", name: "Phường Trần Phú" },
    { id: "p11", name: "Phường Bạch Đằng" },
  ],
  ct_qn: [
    { id: "x1", name: "Xã Cô Tô" },
    { id: "x2", name: "Xã Tân Thanh" },
    { id: "x3", name: "Xã Tây An" },
    { id: "x4", name: "Xã Quảng Sơn" },
  ],

  // ======================== QUẢNG TRỊ ========================
  qt: [
    { id: "p1", name: "Phường Đông Hà" },
    { id: "p2", name: "Phường Hải Thượng" },
    { id: "p3", name: "Phường Bắc Sơn" },
    { id: "p4", name: "Phường Tây Sơn" },
    { id: "p5", name: "Phường Tân Phú" },
    { id: "p6", name: "Phường Minh Khai" },
    { id: "p7", name: "Phường Bình Minh" },
    { id: "p8", name: "Phường Dương Quang" },
    { id: "p9", name: "Phường Hải Sơn" },
    { id: "p10", name: "Phường Thanh Bình" },
  ],
  qt_hc: [
    { id: "x1", name: "Xã Quảng Trị" },
    { id: "x2", name: "Xã Tân Thanh" },
    { id: "x3", name: "Xã Tây An" },
    { id: "x4", name: "Xã Quảng Sơn" },
    { id: "x5", name: "Xã Tân Lập" },
  ],

  // ======================== THỪA THIÊN HUẾ ========================
  tth: [
    { id: "p1", name: "Phường Huế" },
    { id: "p2", name: "Phường Bình Phú" },
    { id: "p3", name: "Phường Phú Nhuận" },
    { id: "p4", name: "Phường Tây Sơn" },
    { id: "p5", name: "Phường Tân Phú" },
    { id: "p6", name: "Phường Minh Khai" },
    { id: "p7", name: "Phường Bình Minh" },
    { id: "p8", name: "Phường Dương Quang" },
    { id: "p9", name: "Phường Hải Sơn" },
    { id: "p10", name: "Phường Thanh Bình" },
    { id: "p11", name: "Phường Trung Tâm" },
  ],
  pl: [
    { id: "x1", name: "Xã Phú Lộc" },
    { id: "x2", name: "Xã Tân Thanh" },
    { id: "x3", name: "Xã Tây An" },
    { id: "x4", name: "Xã Quảng Sơn" },
  ],

  // ======================== TIỀN GIANG ========================
  tg: [
    { id: "p1", name: "Phường Mỹ Tho" },
    { id: "p2", name: "Phường Trung Hòa" },
    { id: "p3", name: "Phường Phú Khương" },
    { id: "p4", name: "Phường Tây Sơn" },
    { id: "p5", name: "Phường Tân Phú" },
    { id: "p6", name: "Phường Minh Khai" },
    { id: "p7", name: "Phường Bình Minh" },
    { id: "p8", name: "Phường Dương Quang" },
    { id: "p9", name: "Phường Hải Sơn" },
    { id: "p10", name: "Phường Thanh Bình" },
    { id: "p11", name: "Phường Trung Tâm" },
  ],
  cb_tg: [
    { id: "x1", name: "Xã Cái Bè" },
    { id: "x2", name: "Xã Tân Thanh" },
    { id: "x3", name: "Xã Tây An" },
    { id: "x4", name: "Xã Quảng Sơn" },
  ],

  // ======================== TRÀ VINH ========================
  tv: [
    { id: "p1", name: "Phường Trà Vinh" },
    { id: "p2", name: "Phường Thạnh Phú" },
    { id: "p3", name: "Phường Quốc Thái" },
    { id: "p4", name: "Phường Tây Sơn" },
    { id: "p5", name: "Phường Tân Phú" },
    { id: "p6", name: "Phường Minh Khai" },
    { id: "p7", name: "Phường Bình Minh" },
    { id: "p8", name: "Phường Dương Quang" },
    { id: "p9", name: "Phường Hải Sơn" },
    { id: "p10", name: "Phường Thanh Bình" },
  ],
  tv_hc: [
    { id: "x1", name: "Xã Trà Vinh" },
    { id: "x2", name: "Xã Tân Thanh" },
    { id: "x3", name: "Xã Tây An" },
    { id: "x4", name: "Xã Quảng Sơn" },
  ],

  // ======================== TUYÊN QUANG ========================
  tq: [
    { id: "p1", name: "Phường Tuyên Quang" },
    { id: "p2", name: "Phường Thành Công" },
    { id: "p3", name: "Phường Tây Sơn" },
    { id: "p4", name: "Phường Tân Phú" },
    { id: "p5", name: "Phường Minh Khai" },
    { id: "p6", name: "Phường Bình Minh" },
    { id: "p7", name: "Phường Dương Quang" },
    { id: "p8", name: "Phường Hải Sơn" },
  ],
  tq_hc: [
    { id: "x1", name: "Xã Tuyên Quang" },
    { id: "x2", name: "Xã Tân Thanh" },
    { id: "x3", name: "Xã Tây An" },
    { id: "x4", name: "Xã Quảng Sơn" },
  ],

  // ======================== VĨNH LONG ========================
  vl: [
    { id: "p1", name: "Phường Vĩnh Long" },
    { id: "p2", name: "Phường Mỹ Long" },
    { id: "p3", name: "Phường Long Tho" },
    { id: "p4", name: "Phường Tây Sơn" },
    { id: "p5", name: "Phường Tân Phú" },
    { id: "p6", name: "Phường Minh Khai" },
    { id: "p7", name: "Phường Bình Minh" },
    { id: "p8", name: "Phường Dương Quang" },
    { id: "p9", name: "Phường Hải Sơn" },
    { id: "p10", name: "Phường Thanh Bình" },
    { id: "p11", name: "Phường Trung Tâm" },
  ],
  vl_hc: [
    { id: "x1", name: "Xã Vĩnh Long" },
    { id: "x2", name: "Xã Tân Thanh" },
    { id: "x3", name: "Xã Tây An" },
    { id: "x4", name: "Xã Quảng Sơn" },
    { id: "x5", name: "Xã Tân Lập" },
  ],

  // ======================== VĨNH PHÚC ========================
  vp: [
    { id: "p1", name: "Phường Vĩnh Phúc" },
    { id: "p2", name: "Phường Tân Dương" },
    { id: "p3", name: "Phường Hoàng Văn Thụ" },
    { id: "p4", name: "Phường Tây Sơn" },
    { id: "p5", name: "Phường Tân Phú" },
    { id: "p6", name: "Phường Minh Khai" },
    { id: "p7", name: "Phường Bình Minh" },
    { id: "p8", name: "Phường Dương Quang" },
    { id: "p9", name: "Phường Hải Sơn" },
    { id: "p10", name: "Phường Thanh Bình" },
    { id: "p11", name: "Phường Trung Tâm" },
  ],
  vp_hc: [
    { id: "x1", name: "Xã Vĩnh Phúc" },
    { id: "x2", name: "Xã Tân Thanh" },
    { id: "x3", name: "Xã Tây An" },
    { id: "x4", name: "Xã Quảng Sơn" },
    { id: "x5", name: "Xã Tân Lập" },
  ],

  // ======================== YÊN BÁI ========================
  yb: [
    { id: "p1", name: "Phường Yên Bái" },
    { id: "p2", name: "Phường Trần Phú" },
    { id: "p3", name: "Phường Thượng Thái" },
    { id: "p4", name: "Phường Tây Sơn" },
    { id: "p5", name: "Phường Tân Phú" },
    { id: "p6", name: "Phường Minh Khai" },
    { id: "p7", name: "Phường Bình Minh" },
    { id: "p8", name: "Phường Dương Quang" },
    { id: "p9", name: "Phường Hải Sơn" },
    { id: "p10", name: "Phường Thanh Bình" },
    { id: "p11", name: "Phường Trung Tâm" },
  ],
  yb_hc: [
    { id: "x1", name: "Xã Yên Bái" },
    { id: "x2", name: "Xã Tân Thanh" },
    { id: "x3", name: "Xã Tây An" },
    { id: "x4", name: "Xã Quảng Sơn" },
    { id: "x5", name: "Xã Tân Lập" },
  ],

  // ======================== SÓC TRĂNG ========================
  sg: [
    { id: "p1", name: "Phường Sóc Trăng" },
    { id: "p2", name: "Phường Mỹ Xuyên" },
    { id: "p3", name: "Phường Thanh Bình" },
    { id: "p4", name: "Phường Tây Sơn" },
    { id: "p5", name: "Phường Tân Phú" },
    { id: "p6", name: "Phường Minh Khai" },
    { id: "p7", name: "Phường Bình Minh" },
    { id: "p8", name: "Phường Dương Quang" },
    { id: "p9", name: "Phường Hải Sơn" },
    { id: "p10", name: "Phường Thanh Sơn" },
    { id: "p11", name: "Phường Trung Tâm" },
  ],
  sg_hc: [
    { id: "x1", name: "Xã Sóc Trăng" },
    { id: "x2", name: "Xã Tân Thanh" },
    { id: "x3", name: "Xã Tây An" },
    { id: "x4", name: "Xã Quảng Sơn" },
  ],

  // ======================== SƠN LA ========================
  sl: [
    { id: "p1", name: "Phường Sơn La" },
    { id: "p2", name: "Phường Thành Phố" },
    { id: "p3", name: "Phường Quang Chinh" },
    { id: "p4", name: "Phường Tây Sơn" },
    { id: "p5", name: "Phường Tân Phú" },
    { id: "p6", name: "Phường Minh Khai" },
    { id: "p7", name: "Phường Bình Minh" },
    { id: "p8", name: "Phường Dương Quang" },
    { id: "p9", name: "Phường Hải Sơn" },
  ],
  sl_hc: [
    { id: "x1", name: "Xã Sơn La" },
    { id: "x2", name: "Xã Tân Thanh" },
    { id: "x3", name: "Xã Tây An" },
    { id: "x4", name: "Xã Quảng Sơn" },
  ],

  // ======================== TÂY NINH ========================
  tn: [
    { id: "p1", name: "Phường Tây Ninh" },
    { id: "p2", name: "Phường Bình Hòa" },
    { id: "p3", name: "Phường Lộc Ninh" },
    { id: "p4", name: "Phường Tây Sơn" },
    { id: "p5", name: "Phường Tân Phú" },
    { id: "p6", name: "Phường Minh Khai" },
    { id: "p7", name: "Phường Bình Minh" },
    { id: "p8", name: "Phường Dương Quang" },
    { id: "p9", name: "Phường Hải Sơn" },
    { id: "p10", name: "Phường Thanh Bình" },
  ],
  tn_hc: [
    { id: "x1", name: "Xã Tây Ninh" },
    { id: "x2", name: "Xã Tân Thanh" },
    { id: "x3", name: "Xã Tây An" },
    { id: "x4", name: "Xã Quảng Sơn" },
    { id: "x5", name: "Xã Tân Lập" },
  ],

  // ======================== THÁI BÌNH ========================
  thb: [
    { id: "p1", name: "Phường Thái Bình" },
    { id: "p2", name: "Phường Hợp Lý" },
    { id: "p3", name: "Phường Kỳ Hòa" },
    { id: "p4", name: "Phường Tây Sơn" },
    { id: "p5", name: "Phường Tân Phú" },
    { id: "p6", name: "Phường Minh Khai" },
    { id: "p7", name: "Phường Bình Minh" },
    { id: "p8", name: "Phường Dương Quang" },
    { id: "p9", name: "Phường Hải Sơn" },
    { id: "p10", name: "Phường Thanh Bình" },
    { id: "p11", name: "Phường Trung Tâm" },
  ],
  thb_hc: [
    { id: "x1", name: "Xã Thái Bình" },
    { id: "x2", name: "Xã Tân Thanh" },
    { id: "x3", name: "Xã Tây An" },
    { id: "x4", name: "Xã Quảng Sơn" },
    { id: "x5", name: "Xã Tân Lập" },
  ],

  // ======================== THÁI NGUYÊN ========================
  thn: [
    { id: "p1", name: "Phường Thái Nguyên" },
    { id: "p2", name: "Phường Trung Thành" },
    { id: "p3", name: "Phường Tích Lương" },
    { id: "p4", name: "Phường Tây Sơn" },
    { id: "p5", name: "Phường Tân Phú" },
    { id: "p6", name: "Phường Minh Khai" },
    { id: "p7", name: "Phường Bình Minh" },
    { id: "p8", name: "Phường Dương Quang" },
    { id: "p9", name: "Phường Hải Sơn" },
    { id: "p10", name: "Phường Thanh Bình" },
    { id: "p11", name: "Phường Trung Tâm" },
  ],
  thn_hc: [
    { id: "x1", name: "Xã Thái Nguyên" },
    { id: "x2", name: "Xã Tân Thanh" },
    { id: "x3", name: "Xã Tây An" },
    { id: "x4", name: "Xã Quảng Sơn" },
    { id: "x5", name: "Xã Tân Lập" },
  ],

  // ======================== THANH HÓA ========================
  // TP. Thanh Hóa
  th_tp: [
    { id: "p1", name: "Phường Quảng Cộng" },
    { id: "p2", name: "Phường Lê Lợi" },
    { id: "p3", name: "Phường Trần Phú" },
    { id: "p4", name: "Phường Điện Biên" },
    { id: "p5", name: "Phường Quang Trung" },
    { id: "p6", name: "Phường Hải Bình" },
    { id: "p7", name: "Phường Quảng Cơ" },
    { id: "p8", name: "Phường Ngô Quyền" },
    { id: "p9", name: "Phường Tân Thành" },
    { id: "p10", name: "Phường Hội Thương" },
    { id: "p11", name: "Phường Hải Cường" },
    { id: "p12", name: "Phường Ngô Sỹ Liên" },
  ],

  // TP. Bỉm Sơn
  bm_tp: [
    { id: "p1", name: "Phường Quảng Hà" },
    { id: "p2", name: "Phường Quảng Phong" },
    { id: "p3", name: "Phường Bạch Đằng" },
    { id: "p4", name: "Phường Bình Minh" },
    { id: "p5", name: "Phường Đập Chiêu" },
    { id: "p6", name: "Phường Tây Sơn" },
    { id: "p7", name: "Phường Thái Sơn" },
    { id: "p8", name: "Phường Hồng Sơn" },
  ],

  // TP. Sâm Sơn
  ss_tp: [
    { id: "p1", name: "Phường Quảng Cửu" },
    { id: "p2", name: "Phường Quảng Đông" },
    { id: "p3", name: "Phường Hải Sơn" },
    { id: "p4", name: "Phường Hải Thành" },
    { id: "p5", name: "Phường Hải Tân" },
    { id: "p6", name: "Phường Hải Phương" },
    { id: "p7", name: "Phường Kỳ Anh" },
  ],

  // Huyện Hậu Lộc
  hl_hc: [
    { id: "x1", name: "Xã Hậu Lộc" },
    { id: "x2", name: "Xã Cao Dương" },
    { id: "x3", name: "Xã Đông Kiều" },
    { id: "x4", name: "Xã Hòa Bình" },
    { id: "x5", name: "Xã Tây Sơn" },
    { id: "x6", name: "Xã Bích Sơn" },
    { id: "x7", name: "Xã Hoà Long" },
    { id: "x8", name: "Xã Tân Phú" },
    { id: "x9", name: "Xã Châu Phong" },
    { id: "x10", name: "Xã Hòa Mỹ" },
    { id: "x11", name: "Xã Liêm Phong" },
    { id: "x12", name: "Xã Yên Phong" },
  ],

  // Huyện Hoằng Hóa
  hh_hc: [
    { id: "x1", name: "Xã Hoằng Hóa" },
    { id: "x2", name: "Xã Hoằng Trường" },
    { id: "x3", name: "Xã Hoằng Thị" },
    { id: "x4", name: "Xã Hoằng Tâm" },
    { id: "x5", name: "Xã Hoằng Châu" },
    { id: "x6", name: "Xã Hoằng Hải" },
    { id: "x7", name: "Xã Hoằng Quế" },
    { id: "x8", name: "Xã Hoằng Sơn" },
    { id: "x9", name: "Xã Liêm Thắng" },
    { id: "x10", name: "Xã Liêm Phong" },
    { id: "x11", name: "Xã Liêm Hải" },
    { id: "x12", name: "Xã Minh Phong" },
  ],

  // Huyện Tĩnh Gia
  tg_hc: [
    { id: "x1", name: "Xã Tĩnh Gia" },
    { id: "x2", name: "Xã Tĩnh Hải" },
    { id: "x3", name: "Xã Tĩnh Thịnh" },
    { id: "x4", name: "Xã Tĩnh Toàn" },
    { id: "x5", name: "Xã Tĩnh Phong" },
    { id: "x6", name: "Xã Tĩnh Minh" },
    { id: "x7", name: "Xã Tĩnh Hồng" },
    { id: "x8", name: "Xã Tĩnh Dân" },
    { id: "x9", name: "Xã Lương Xá" },
    { id: "x10", name: "Xã Liên Hoa" },
    { id: "x11", name: "Xã Liên Mỹ" },
    { id: "x12", name: "Xã Phúc Thọ" },
  ],

  // Huyện Yên Định
  yd_hc: [
    { id: "x1", name: "Xã Yên Định" },
    { id: "x2", name: "Xã Yên Sơn" },
    { id: "x3", name: "Xã Yên Thái" },
    { id: "x4", name: "Xã Yên Khánh" },
    { id: "x5", name: "Xã Yên Hòa" },
    { id: "x6", name: "Xã Quảng Phú" },
    { id: "x7", name: "Xã Minh Khai" },
    { id: "x8", name: "Xã Tuyên Sơn" },
    { id: "x9", name: "Xã Cúc Sơn" },
    { id: "x10", name: "Xã Đức Minh" },
    { id: "x11", name: "Xã Xuân Lâm" },
    { id: "x12", name: "Xã Hải Yên" },
  ],

  // Huyện Nông Cống
  nc_hc: [
    { id: "x1", name: "Xã Nông Cống" },
    { id: "x2", name: "Xã Nông Thân" },
    { id: "x3", name: "Xã Thái Hòa" },
    { id: "x4", name: "Xã Công Sơn" },
    { id: "x5", name: "Xã Quyền Phú" },
    { id: "x6", name: "Xã Xuân Hòa" },
    { id: "x7", name: "Xã Phong Châu" },
    { id: "x8", name: "Xã Lưu Xá" },
    { id: "x9", name: "Xã Bảo Hòa" },
    { id: "x10", name: "Xã Yên Hồng" },
    { id: "x11", name: "Xã Kim Sơn" },
  ],

  // Huyện Vĩnh Lộc
  vl_hc: [
    { id: "x1", name: "Xã Vĩnh Lộc" },
    { id: "x2", name: "Xã Vĩnh Thịnh" },
    { id: "x3", name: "Xã Vĩnh Phú" },
    { id: "x4", name: "Xã Vĩnh Sơn" },
    { id: "x5", name: "Xã Vĩnh Lâm" },
    { id: "x6", name: "Xã Vĩnh Tân" },
    { id: "x7", name: "Xã Vĩnh Hùng" },
    { id: "x8", name: "Xã Vĩnh Hòa" },
    { id: "x9", name: "Xã Liên Mạc" },
    { id: "x10", name: "Xã Liên Sơn" },
    { id: "x11", name: "Xã Liên Xá" },
    { id: "x12", name: "Xã Phúc Lộc" },
  ],

  // Huyện Quảng Xương
  qx_hc: [
    { id: "x1", name: "Xã Quảng Xương" },
    { id: "x2", name: "Xã Quảng Thanh" },
    { id: "x3", name: "Xã Quảng Hòa" },
    { id: "x4", name: "Xã Quảng Sơn" },
    { id: "x5", name: "Xã Quảng Tú" },
    { id: "x6", name: "Xã Quảng Phong" },
    { id: "x7", name: "Xã Quảng Lợi" },
    { id: "x8", name: "Xã Quảng Thái" },
    { id: "x9", name: "Xã Quảng Dương" },
    { id: "x10", name: "Xã Liên Hà" },
    { id: "x11", name: "Xã Liên Sơn" },
    { id: "x12", name: "Xã Liên Hợp" },
  ],

  // Huyện Đông Sơn
  ds_hc: [
    { id: "x1", name: "Xã Đông Sơn" },
    { id: "x2", name: "Xã Đông Hòa" },
    { id: "x3", name: "Xã Đông Thái" },
    { id: "x4", name: "Xã Đông Thắng" },
    { id: "x5", name: "Xã Đông Ngạn" },
    { id: "x6", name: "Xã Đông Kiên" },
    { id: "x7", name: "Xã Tây Sơn" },
    { id: "x8", name: "Xã Tây Hòa" },
    { id: "x9", name: "Xã Hòa Bình" },
    { id: "x10", name: "Xã Hòa Sơn" },
    { id: "x11", name: "Xã Thanh Bình" },
  ],

  // Huyện Như Xuân
  nx_hc: [
    { id: "x1", name: "Xã Như Xuân" },
    { id: "x2", name: "Xã Như Sơn" },
    { id: "x3", name: "Xã Như Hòa" },
    { id: "x4", name: "Xã Như Thái" },
    { id: "x5", name: "Xã Như Phú" },
    { id: "x6", name: "Xã Như Lâm" },
    { id: "x7", name: "Xã Như Long" },
    { id: "x8", name: "Xã Như Hương" },
    { id: "x9", name: "Xã Liên Hà" },
    { id: "x10", name: "Xã Liên Sơn" },
  ],

  // Huyện Cẩm Thủy
  ct_hc: [
    { id: "x1", name: "Xã Cẩm Thủy" },
    { id: "x2", name: "Xã Cẩm Sơn" },
    { id: "x3", name: "Xã Cẩm Hòa" },
    { id: "x4", name: "Xã Cẩm Phong" },
    { id: "x5", name: "Xã Cẩm Thanh" },
    { id: "x6", name: "Xã Cẩm Lâm" },
    { id: "x7", name: "Xã Cẩm Tân" },
    { id: "x8", name: "Xã Cẩm Hưng" },
    { id: "x9", name: "Xã Liên Hà" },
    { id: "x10", name: "Xã Liên Sơn" },
  ],

  // ======================== THỪA THIÊN HUẾ (TP Huế) ========================
  hue_ct: [
    { id: "p1", name: "Phường Huế" },
    { id: "p2", name: "Phường Bình Phú" },
    { id: "p3", name: "Phường Phú Nhuận" },
    { id: "p4", name: "Phường Tây Sơn" },
    { id: "p5", name: "Phường Tân Phú" },
    { id: "p6", name: "Phường Minh Khai" },
    { id: "p7", name: "Phường Bình Minh" },
    { id: "p8", name: "Phường Dương Quang" },
    { id: "p9", name: "Phường Hải Sơn" },
    { id: "p10", name: "Phường Thanh Bình" },
    { id: "p11", name: "Phường Trung Tâm" },
  ],

  // ======================== TIỀN GIANG (TP Mỹ Tho) ========================
  mt_ct: [
    { id: "p1", name: "Phường Mỹ Tho" },
    { id: "p2", name: "Phường Trung Hòa" },
    { id: "p3", name: "Phường Phú Khương" },
    { id: "p4", name: "Phường Tây Sơn" },
    { id: "p5", name: "Phường Tân Phú" },
    { id: "p6", name: "Phường Minh Khai" },
    { id: "p7", name: "Phường Bình Minh" },
    { id: "p8", name: "Phường Dương Quang" },
    { id: "p9", name: "Phường Hải Sơn" },
    { id: "p10", name: "Phường Thanh Bình" },
    { id: "p11", name: "Phường Trung Tâm" },
    { id: "p12", name: "Phường Cái Dầu" },
  ],

  // ======================== TRÀ VINH (TP Trà Vinh) ========================
  tv_ct: [
    { id: "p1", name: "Phường Trà Vinh" },
    { id: "p2", name: "Phường Thạnh Phú" },
    { id: "p3", name: "Phường Quốc Thái" },
    { id: "p4", name: "Phường Tây Sơn" },
    { id: "p5", name: "Phường Tân Phú" },
    { id: "p6", name: "Phường Minh Khai" },
    { id: "p7", name: "Phường Bình Minh" },
    { id: "p8", name: "Phường Dương Quang" },
    { id: "p9", name: "Phường Hải Sơn" },
    { id: "p10", name: "Phường Thanh Bình" },
    { id: "p11", name: "Phường Trung Tâm" },
    { id: "p12", name: "Phường Cái Dầu" },
  ],

  // ======================== TUYÊN QUANG (TP Tuyên Quang) ========================
  tq_ct: [
    { id: "p1", name: "Phường Tuyên Quang" },
    { id: "p2", name: "Phường Thành Công" },
    { id: "p3", name: "Phường Tây Sơn" },
    { id: "p4", name: "Phường Tân Phú" },
    { id: "p5", name: "Phường Minh Khai" },
    { id: "p6", name: "Phường Bình Minh" },
    { id: "p7", name: "Phường Dương Quang" },
    { id: "p8", name: "Phường Hải Sơn" },
  ],

  // ======================== VĨNH LONG (TP Vĩnh Long) ========================
  vl_ct: [
    { id: "p1", name: "Phường Vĩnh Long" },
    { id: "p2", name: "Phường Mỹ Long" },
    { id: "p3", name: "Phường Long Tho" },
    { id: "p4", name: "Phường Tây Sơn" },
    { id: "p5", name: "Phường Tân Phú" },
    { id: "p6", name: "Phường Minh Khai" },
    { id: "p7", name: "Phường Bình Minh" },
    { id: "p8", name: "Phường Dương Quang" },
    { id: "p9", name: "Phường Hải Sơn" },
    { id: "p10", name: "Phường Thanh Bình" },
    { id: "p11", name: "Phường Trung Tâm" },
    { id: "p12", name: "Phường Cái Dầu" },
  ],

  // ======================== VĨNH PHÚC (TP Vĩnh Phúc) ========================
  vp_ct: [
    { id: "p1", name: "Phường Vĩnh Phúc" },
    { id: "p2", name: "Phường Tân Dương" },
    { id: "p3", name: "Phường Hoàng Văn Thụ" },
    { id: "p4", name: "Phường Tây Sơn" },
    { id: "p5", name: "Phường Tân Phú" },
    { id: "p6", name: "Phường Minh Khai" },
    { id: "p7", name: "Phường Bình Minh" },
    { id: "p8", name: "Phường Dương Quang" },
    { id: "p9", name: "Phường Hải Sơn" },
    { id: "p10", name: "Phường Thanh Bình" },
    { id: "p11", name: "Phường Trung Tâm" },
    { id: "p12", name: "Phường Cái Dầu" },
  ],

  // ======================== YÊN BÁI (TP Yên Bái) ========================
  yb_ct: [
    { id: "p1", name: "Phường Yên Bái" },
    { id: "p2", name: "Phường Trần Phú" },
    { id: "p3", name: "Phường Thượng Thái" },
    { id: "p4", name: "Phường Tây Sơn" },
    { id: "p5", name: "Phường Tân Phú" },
    { id: "p6", name: "Phường Minh Khai" },
    { id: "p7", name: "Phường Bình Minh" },
    { id: "p8", name: "Phường Dương Quang" },
    { id: "p9", name: "Phường Hải Sơn" },
    { id: "p10", name: "Phường Thanh Bình" },
    { id: "p11", name: "Phường Trung Tâm" },
  ],

  // ======================== SÓC TRĂNG (TP Sóc Trăng) ========================
  sg_ct: [
    { id: "p1", name: "Phường Sóc Trăng" },
    { id: "p2", name: "Phường Mỹ Xuyên" },
    { id: "p3", name: "Phường Thanh Bình" },
    { id: "p4", name: "Phường Tây Sơn" },
    { id: "p5", name: "Phường Tân Phú" },
    { id: "p6", name: "Phường Minh Khai" },
    { id: "p7", name: "Phường Bình Minh" },
    { id: "p8", name: "Phường Dương Quang" },
    { id: "p9", name: "Phường Hải Sơn" },
    { id: "p10", name: "Phường Thanh Sơn" },
    { id: "p11", name: "Phường Trung Tâm" },
    { id: "p12", name: "Phường Cái Dầu" },
  ],

  // ======================== SƠN LA (TP Sơn La) ========================
  sl_ct: [
    { id: "p1", name: "Phường Sơn La" },
    { id: "p2", name: "Phường Thành Phố" },
    { id: "p3", name: "Phường Quang Chinh" },
    { id: "p4", name: "Phường Tây Sơn" },
    { id: "p5", name: "Phường Tân Phú" },
    { id: "p6", name: "Phường Minh Khai" },
    { id: "p7", name: "Phường Bình Minh" },
    { id: "p8", name: "Phường Dương Quang" },
    { id: "p9", name: "Phường Hải Sơn" },
    { id: "p10", name: "Phường Thanh Bình" },
  ],

  // ======================== TÂY NINH (TP Tây Ninh) ========================
  tn_ct: [
    { id: "p1", name: "Phường Tây Ninh" },
    { id: "p2", name: "Phường Bình Hòa" },
    { id: "p3", name: "Phường Lộc Ninh" },
    { id: "p4", name: "Phường Tây Sơn" },
    { id: "p5", name: "Phường Tân Phú" },
    { id: "p6", name: "Phường Minh Khai" },
    { id: "p7", name: "Phường Bình Minh" },
    { id: "p8", name: "Phường Dương Quang" },
    { id: "p9", name: "Phường Hải Sơn" },
    { id: "p10", name: "Phường Thanh Bình" },
    { id: "p11", name: "Phường Trung Tâm" },
  ],

  // ======================== THÁI BÌNH (TP Thái Bình) ========================
  thb_ct: [
    { id: "p1", name: "Phường Thái Bình" },
    { id: "p2", name: "Phường Hợp Lý" },
    { id: "p3", name: "Phường Kỳ Hòa" },
    { id: "p4", name: "Phường Tây Sơn" },
    { id: "p5", name: "Phường Tân Phú" },
    { id: "p6", name: "Phường Minh Khai" },
    { id: "p7", name: "Phường Bình Minh" },
    { id: "p8", name: "Phường Dương Quang" },
    { id: "p9", name: "Phường Hải Sơn" },
    { id: "p10", name: "Phường Thanh Bình" },
    { id: "p11", name: "Phường Trung Tâm" },
    { id: "p12", name: "Phường Cái Dầu" },
  ],

  // ======================== THÁI NGUYÊN (TP Thái Nguyên) ========================
  thn_ct: [
    { id: "p1", name: "Phường Thái Nguyên" },
    { id: "p2", name: "Phường Trung Thành" },
    { id: "p3", name: "Phường Tích Lương" },
    { id: "p4", name: "Phường Tây Sơn" },
    { id: "p5", name: "Phường Tân Phú" },
    { id: "p6", name: "Phường Minh Khai" },
    { id: "p7", name: "Phường Bình Minh" },
    { id: "p8", name: "Phường Dương Quang" },
    { id: "p9", name: "Phường Hải Sơn" },
    { id: "p10", name: "Phường Thanh Bình" },
    { id: "p11", name: "Phường Trung Tâm" },
    { id: "p12", name: "Phường Cái Dầu" },
  ],
};
